(function(h,f,q){h.SPR||(h.SPR={provide:function(a,d){b[a]||(b[a]=d,"function"===typeof b[a].init&&b[a].init())}});var b=h.SPR;b.provide("Common",{random:function(){return Math.floor(8675309*Math.random())},isArray:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},hasOwnProperty:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}});b.provide("DOM",{init:function(){function a(){b.DOM.flush();
h.removeEventListener("DOMContentLoaded",a,!1)}function d(){/loaded|interactive|complete/.test(f.readyState)&&(f.detachEvent("onreadystatechange",d),c&&(c=!1,b.DOM.flush()))}b.DOM.on=b.DOM.attachEvent;b.DOM.off=b.DOM.detachEvent;var c=!0;h.addEventListener&&h.addEventListener("DOMContentLoaded",a);f.attachEvent&&f.attachEvent("onreadystatechange",d);b.DOM.hidden=!1},onTabChange:function(a,b){function c(c){c=c||h.event;return c.type in n?n[c.type]===e?b():a():f[g]?b():a()}var e="hidden",g=e,n={focus:"visible",
focusin:"visible",pageshow:"visible",blur:e,focusout:e,pagehide:e};g in f?f.addEventListener("visibilitychange",c):(g="mozHidden")in f?f.addEventListener("mozvisibilitychange",c):(g="webkitHidden")in f?f.addEventListener("webkitvisibilitychange",c):(g="msHidden")in f?f.addEventListener("msvisibilitychange",c):"onfocusin"in f?f.onfocusin=f.onfocusout=c:h.onpageshow=h.onpagehide=h.onfocus=h.onblur=c},addIframeSync:function(a){var d=f.createElement("iframe"),c=f.body;d.setAttribute("name","spr");d.src=
a;d.setAttribute("height","1");d.setAttribute("width","1");d.setAttribute("visible","false");d.style.display="none";c||(c=b.DOM.$("BODY")[0]);c||(c=b.DOM.$("HEAD")[0]);c.appendChild(d);return d},addScript:function(a){var d=f.createElement("script");d.type="text/javascript";d.setAttribute("async",!0);d.setAttribute("name","spr");d.src=a;b.DOM.onReady(function(){setTimeout(function(){b.DOM.$("HEAD")[0].appendChild(d)},1)});return d},queue:[],ready:/loaded|interactive|complete/.test(f.readyState),flush:function(){var a=
b.DOM.queue.shift();for(b.DOM.ready=!0;a;)a(),a=b.DOM.queue.shift()},onReady:function(a){b.DOM.ready?(b.DOM.queue.push(a),b.DOM.flush()):f.documentElement.doScroll?h.self===h.top?function(){if(!f.uniqueID&&f.expando)return b.DOM.queue.push(a);try{f.documentElement.doScroll("left"),a()}catch(d){setTimeout(arguments.callee,0)}}():b.DOM.queue.push(a):b.DOM.queue.push(a)},attachEvent:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},detachEvent:function(a,
b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},top:function(a){return a?a.y?a.y:a.offsetTop+b.DOM.top(a.offsetParent):0},left:function(a){return a?a.x?a.x:a.offsetLeft+b.DOM.left(a.offsetParent):0},height:function(a){return Math.max(a.scrollHeight||0,a.offsetHeight||0,a.clientHeight||0)},width:function(a){return Math.max(a.scrollWidth||0,a.offsetWidth||0,a.clientWidth||0)},scroll:function(){var a=0;return a=h.pageYOffset?h.pageYOffset:f.documentElement?f.documentElement.scrollTop:
0},viewport:function(){var a=0,d=0,d=f.documentElement;h.innerWidth?(a=h.innerWidth,d=h.innerHeight):(d&&d.clientWidth||(d=b.$("BODY")[0]),a=d.clientWidth,d=d.clientHeight);return{w:a,h:d}},getsupportedprop:function(a){for(var b=f.documentElement,c=0;c<a.length;c++)if("string"==typeof b.style[a[c]])return a[c]},$:function(a){var b=[],c,e=0,g;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(f.getElementById(a.substring(1)));break;case ".":c=f.getElementsByTagName("*");
for(g=" "+a.substring(1)+" ";e<c.length;e+=1)a=(" "+c[e].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(g)&&b.push(c[e]);break;default:b=f.getElementsByTagName(a)}return b}});b.provide("QS",{escape:function(a){return encodeURIComponent(a)},unescape:function(a){return decodeURIComponent(a)},encode:function(a,d){var c=b.QS,e=[];if(b.Common.isArray(a))for(var g=0,f;g<a.length;g+=1)f=a[g],/\[\]$/.test(d)?e.push(c.escape(d)+"="+c.escape(f)):e.push(c.encode(f,d+"["+("object"===typeof f?g:"")+"]"));
else if("object"!==typeof a||null===a||"nodeType"in a)e.push(c.escape(d)+"="+c.escape(a));else for(g in a)Object.prototype.hasOwnProperty.call(a,g)&&(d?e.push(c.encode(a[g],d+"["+g+"]")):e.push(c.encode(a[g],g)));return e.join("&")},decode:function(a){var d={},c=0,e={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var g=a[c].split("="),f=b.QS.unescape(g[0]),h=d,k=0,l=f.split("]["),p=l.length-1;/\[/.test(l[0])&&/\]$/.test(l[p])?(l[p]=l[p].replace(/\]$/,""),
l=l.shift().split("[").concat(l),p=l.length-1):p=0;if(2===g.length)if(g=(g=b.QS.unescape(g[1]))&&!isNaN(g)?+g:"undefined"===g?void 0:void 0!==e[g]?e[g]:g,p)for(;k<=p;k+=1)f=""===l[k]?h.length:l[k],h=h[f]=k<p?h[f]||(l[k+1]&&isNaN(l[k+1])?{}:[]):g;else b.Common.isArray(d[f])?d[f].push(g):d[f]=void 0!==d[f]?[d[f],g]:g;else f&&(d[f]=void 0)}return d}});b.provide("API",{callbacks:{},jsonp:function(a,d,c,e,g){e=e||q;g||(g="cb");var f="cb"+b.Common.random(),m=b.API;c[g]="SPR.API.callbacks."+f;g=h.location.protocol+
"//";"file://"===g&&(g="http://");c=b.QS.encode(c);var k=b.DOM.addScript(g+a+d+"?"+c);m.callbacks[f]=function(a){setTimeout(function(){k.parentNode.removeChild(k)},0);e(a);try{delete m.callbacks[f]}catch(b){m.callbacks[f]=null}}},track:function(a,d,c,e){var f;if("undefined"===typeof XMLHttpRequest)for(var n=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],m=0;m<n.length;m+=1)try{if(f=new h.ActiveXObject(n[m]))break}catch(k){}else f=new XMLHttpRequest;n=h.location.protocol+
"//";c=b.QS.encode(c);"file://"===n&&(n="http://");a=n+a+d+"?"+c;f?(f.open("POST",a,!0),f.send()):h.location.replace(a);e()}});b.provide("Cookie",{patterns:{},get:function(a){var d=f.cookie||"",c=b.Cookie.patterns[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),b.Cookie.patterns[a]=c);return(a=d.match(c))&&b.QS.unescape(a[1])},set:function(a,b,c){var e="";c&&(e="; expires="+c.toGMTString());f.cookie=a+"="+b+e+"; path=/"},del:function(a){b.Cookie.set(a,
"",new Date(1982,5,13))}});b.provide("de",{api:"feeds.delicious.com",apiPath:"/v2/json/urlinfo/data",collect:function(a){var d=b.de;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"de",data:c})},"callback")}});b.provide("dg",{api:"services.digg.com",apiPath:"/stories/",collect:function(a){var d=b.dg;b.API.jsonp(d.api,d.apiPath,{type:"javascript",link:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",
{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"dg",data:c})},"callback")}});b.provide("fb",{api:"graph.facebook.com",apiPath:"/fql",collect:function(a){var d=b.fb;b.API.jsonp(d.api,d.apiPath,{q:'SELECT url,total_count,share_count,comment_count,like_count,click_count,commentsbox_count FROM link_stat WHERE url in ("'+a.url+'")'},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"fb",data:c})},"callback")}});b.provide("gp",{api:"clients6.google.com",apiPath:"rpc",
collect:function(a){}});b.provide("li",{api:"www.linkedin.com",apiPath:"/countserv/count/share",collect:function(a){var d=b.li;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"li",data:c})},"callback")}});b.provide("rd",{api:"www.reddit.com",apiPath:"/api/info.json",collect:function(a){var d=b.rd;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,
cid:a.id,pid:a.pid,sn:"rd",data:c})},"jsonp")}});b.provide("pi",{api:"partners-api.pinterest.com",apiPath:"/v1/urls/count.json",collect:function(a){var d=b.pi;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"pi",data:c})},"callback")}});b.provide("su",{api:"www.stumbleupon.com",apiPath:"/services/1.01/badge.getinfo",collect:function(a){var d=b.su;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com",
"/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"su",data:c})})}});b.provide("tw",{api:"urls.api.twitter.com",apiPath:"/1/urls/count.json",collect:function(a){var d=b.tw;b.API.jsonp(d.api,d.apiPath,{url:a.url},function(c){b.API.jsonp("cc.simplereach.com","/event",{event:"s",url:a.url,cid:a.id,pid:a.pid,sn:"tw",data:c})},"callback")}});b.provide("Reach",{api:"cc.simplereach.com",cdn:"d8rk54i4mohrb.cloudfront.net",config:{},init:function(){if(h.location.host!==b.Reach.cdn)try{var a=b.Reach,d=h.__reach_config||
h.__spr_config,c=a.config||{},e;for(e in d)void 0===c[e]&&(c[e]=d[e]);c.ckw&&(c.tags=c.ckw.split(" "));c.pub&&(c.date=c.pub);c.cat&&(c.channels=c.cat.split(" "));if(!0===c.no_slide||1===c.no_slide)c.slide_active=!1;a.config=c;a.collect(c)}catch(g){b.DOM.onReady(function(){var a=f.createElement("img");a.src="http://cc.simplereach.com/pixel?bad=true&error="+g.message;a.setAttribute("width","1px");f.body.appendChild(a)})}},collect:function(a){function d(a){"string"===typeof a&&(a=a.split(","));if(b.Common.isArray(a)){for(var c=
0;c<a.length;c+=1)"string"===typeof a[c]&&(a[c]=a[c].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}return a}var c=b.Reach,e={};e.pid=a.pid;e.url=a.url;e.title=a.title;e.date=a.date;e.domain=a.domain;e.ref_url=a.ref_url;e.referrer=a.referrer||f.referrer;e.page_url=a.page_url||h.location.toString();var g=a.uid||b.Reach.getUserId();g&&(e.uid=g);a.authors&&(e.authors=d(a.authors));a.channels&&(e.channels=d(a.channels));a.tags&&(e.tags=d(a.tags));a.brand_tags&&(e.brand_tags=
d(a.brand_tags));a.date&&"string"!==typeof a.date&&(e.date=a.date.toString());if(null!==e.pid&&void 0!==e.pid&&e.url&&e.date){if(0===e.url.indexOf("http%3"))try{e.url=decodeURIComponent(e.url)}catch(n){e.url=unescape(e.url)}a.url=e.url;if(a.iframe)e.ref_url=e.ref_url||f.referrer,e.cache_buster=(new Date).getTime(),a=b.QS.encode(e),b.DOM.addIframeSync("//"+b.Reach.cdn+"/iframe.html?"+a);else{0===e.pid&&(e.pid="000000000000000000000000");var m=(new Date).getTime();b.API.jsonp(c.api,"/n",e,function(a){c.track(a,
m);a.uid&&c.setUserId(a.uid);if(!1!==a.slide){var d=!1;!0===c.config.slide_active?d=!0:!1!==c.config.slide_active&&!0===a.slide&&(d=!0);b.Slide&&!0===d&&!1===b.Slide.enabled&&b.Slide.enable(a.id)}a.de&&b.de.collect(a);a.dg&&b.dg.collect(a);a.fb&&b.fb.collect(a);a.gp&&b.gp.collect(a);a.li&&b.li.collect(a);a.rd&&b.rd.collect(a);a.su&&b.su.collect(a);a.tw&&b.tw.collect(a);a.pi&&b.pi.collect(a)})}}else if(!a.ignore_errors)try{console.log("SPR-ERROR: Please provide pid, url and date in the configuration")}catch(k){}},
track:function(a,d){b.DOM.addIframeSync("//"+b.Reach.cdn+"/track.html?"+b.QS.encode({event:"tu",id:a.id,url:a.url,pid:a.pid,uid:a.uid,sid:a.sid,vid:a.vid,st:d,tick:0}))},getUserId:function(){return b.Cookie.get("__sruid")},setUserId:function(a){b.Cookie.set("__sruid",a,new Date(2042,5,13))}})})(window,document,function(){});
