/*ebPreServing.js - v_2_11_0_0 - 2014-03-12*/
EBP="undefined"!=typeof EBP?EBP:{};EBP.Light=EBP.Light||{};EBP.Light.Infra=function(){};EBP.Light.Infra.isDefined=function(a){return"undefined"!=typeof a};EBP.Light.Infra.getTimestamp=function(){var a=new Date;return parseInt(a.getHours()+1)+":"+a.getMinutes()+":"+a.getSeconds()+"."+a.getMilliseconds()+" "+a.getDate()+"."+parseInt(a.getMonth()+1)+"."+a.getFullYear()};
EBP.Light.Infra.getUrlParameter=function(a){var c="",b=EBP.Light.Infra.getWindowLocation().toString(),d=RegExp("[&,?]"+a+"=(.*)$","i");if((a=b.match(RegExp("[&,?]"+a+"=(.*)[&]","i"))||b.match(d))&&0<a.length)-1<a[1].indexOf("&")&&(a[1]=a[1].substr(0,a[1].indexOf("&"))),c=a[1];return c};EBP.Light.Infra.combinePaths=function(a,c){a=a||"";c=c||"";a&&"/"!=a[a.length-1]&&(a+="/");var b=a;c&&(b+=c);return b};
EBP.Light.Infra.isPageLoaded=function(){var a=!0;"complete"!=document.readyState&&"loaded"!=document.readyState&&"interactive"!=document.readyState&&(a=!1);return a};EBP.Light.Infra.addChildToPage=function(a,c,b,d){if("undefined"==typeof c||!c)c=document.body||document.getElementsByTagName("head")[0];this.isDefined(b)&&null!=b&&this.addEventListener(a,b,d);c.appendChild(a)};
EBP.Light.Infra.addEventListener=function(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):(c="on"+c,a.attachEvent?a.attachEvent(c,b):c in a&&(a[c]=b))};EBP.Light.Infra.createScriptElement=function(a,c,b,d){try{var e=a.createElement(c);e.type=b;e.src=d;e.async=!1;return e}catch(g){}};
EBP.Light.Infra.addScriptElement=function(a,c){var b;if(c){if(b=c,0==b.childNodes.length){var d=document.createElement("div");d.style.display="none";c.appendChild(d)}}else b=document.head||document.documentElement;b.insertBefore(a,b.firstChild)};EBP.Light.Infra.getWindowLocation=function(){return window.location};EBP.Light.Infra.getRandomNumber=function(){try{var a=Math.random().toString();return a=a.substr(a.indexOf(".")+1)}catch(c){}};
EBP.Light.Infra.getAddInEyeDomain=function(a){var c="",b="",d=0,a=(a?a:window).document,a=a.referrer?a.referrer:a.location.href;try{a=a.toLowerCase(),7<=a.length&&"http://"==a.substr(0,7)?(b=a.substr(7),a.substr(0,7)):8<=a.length&&"https://"==a.substr(0,8)?(b=a.substr(8),a.substr(0,8)):b=a,d=b.indexOf("/"),0<d&&(b=b.substr(0,d)),c=b}catch(e){c=""}return c};
EBP.Light.Infra.createFriendlyIframe=function(a,c,b,d){a=(a?a:document).createElement("iframe");c&&a.setAttribute("id",c);a.style.display=b?"":"none";a.style.width=b?b+"px":"0px";a.style.height=d?d+"px":"0px";document.documentMode&&8>document.documentMode?(a.frameBorder=0,a.margin=0,a.marginWidth=0,a.marginHeight=0,a.scrolling="no"):(a.setAttribute("scrolling","no"),a.setAttribute("marginwidth","0"),a.setAttribute("marginheight","0"),a.setAttribute("frameborder","0"));return a};
EBP.Light.Infra.writeToFriendlyIframe=function(a,c,b){var b=this.isDefined(b)?b:!1,d;d=a.contentWindow?a.contentWindow.document:a.contentDocument&&a.contentDocument.document?a.contentDocument.document:a.contentDocument;d.open().write(c);b&&setTimeout(function(){d.close()},1E3)};
EBP.Light.Infra.createUnfriendlyIframe=function(a,c){if(c&&!EBP.Light.Infra.isPageLoaded())this.logger&&this.logger.info("Adding unfriendly iframe in sync mode, url: "+a),document.write('<iframe src="'+a+'" style="display:none;width:0px;height:0px"></iframe>');else{this.logger&&this.logger.info("Adding unfriendly iframe in async mode, url: "+a);var b=document.createElement("iframe");b.setAttribute("src",a);b.style.display="none";EBP.Light.Infra.addChildToPage(b)}};
EBP.Light.Infra.getTopLevelReferrer=function(a){var c=null;try{a.top&&a.top.document&&a.top.document.referrer&&(c=a.top.document.referrer.toString())}catch(b){}return c};
EBP.Light.Infra.typeOf=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array||!(a instanceof Object)&&"[object Array]"==Object.prototype.toString.call(a)||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&("[object Function]"==Object.prototype.toString.call(a)||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};EBP.Light.Logger=function(a){this._level=a;this.startNestingGroupNames=[];this.endNestingGroupNames=[]};EBP.Light.Logger.DebugMode="mmdebug";EBP.Light.Logger.LoggerLevels={NONE:0,ERROR:1,INFO:2,WARN:3,DEBUG:4};
EBP.Light.Logger.prototype={setLevel:function(a){this._level=a},timestamp:!1,debug:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.DEBUG,arguments)},info:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.INFO,arguments)},warn:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.WARN,arguments)},error:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.ERROR,arguments)},exception:function(a,c){var b="string"!==c?this._format("Exception in {0}. message: {1}",a,c.message):
this._format("Exception in: {0}. message: {1}",a,c);c.stack&&(b+=this._format(" stack: {0}",c.stack));this._reportToLog(EBP.Light.Logger.LoggerLevels.ERROR,[b])},startGroup:function(a){this._supportNesting()&&this.startNestingGroupNames.push(a)},endGroup:function(){this._supportNesting()&&0<this.endNestingGroupNames.length&&window.console.groupEnd(this.endNestingGroupNames.pop())},_consoleAvailable:function(){try{return void 0!==window&&void 0!==window.console}catch(a){return!1}},_supportNesting:function(){return this._consoleAvailable()?
void 0!==window.console.group:!1},_supportErrorMessage:function(){return void 0!==window.console.error},_supportInfoMessage:function(){return void 0!==window.console.info||void 0!==window.opera},_supportWarnMessage:function(){return void 0!==window.console.warn||void 0!==window.opera},_supportObjectView:function(){return void 0!==window.console.dir||void 0!==window.opera},_callConsoleFunction:function(a,c){var b=!1;switch(a){case EBP.Light.Logger.LoggerLevels.INFO:this._supportInfoMessage()&&(window.console.info(c),
b=!0);break;case EBP.Light.Logger.LoggerLevels.WARN:this._supportWarnMessage()&&(window.console.warn(c),b=!0);break;case EBP.Light.Logger.LoggerLevels.ERROR:this._supportErrorMessage()&&(consoleFunction=window.console.error(c),b=!0)}b||window.console.log(c)},_format:function(a){for(var c=1;c<arguments.length;c++)a=a.replace(RegExp("\\{"+(c-1)+"\\}","gi"),""+arguments[c]);return a},_getTimestamp:function(){if(this.timestamp)return EBP.Light.Infra.getTimestamp()},_reportToLog:function(a,c){if(this._level>=
a&&this._consoleAvailable()){var b=c[0];"[object String]"!==Object.prototype.toString.call(b)?this._supportObjectView()||(b=b.toString()):b=this._format.apply(null,c);this.timestamp&&"[object String]"===Object.prototype.toString.call(b)&&(b=this._getTimestamp()+": "+b);if(void 0===window.opera){for(;this.startNestingGroupNames.length;)window.console.group(this.startNestingGroupNames[0]),this.endNestingGroupNames.push(this.startNestingGroupNames.shift());this._callConsoleFunction(a,b)}else opera.postError(b)}}};
var EBPreServing=window.EBPreServing||{};EBPreServing.BandWidthDetection=function(){};
EBPreServing.BandWidthDetection.prototype={checked:!1,checking:!1,speed:0,_adjustment:0.75,_images:[],_loaded:0,_maxSpeed:2E3,_tuneResults:[[150,1.6],[300,1.4],[500,1.3],[800,1],[1E3,0.9],[2E3,0.8]],initImages:function(a,c){this._images=[{path:unescape(a+c+"micro.gif"),bytes:51,start:null,end:null},{path:unescape(a+c+"micro.gif"),bytes:51,start:null,end:null},{path:unescape(a+c+"bw_image.png"),bytes:43677,start:null,end:null}]},_loadImage:function(a){this._images[a].start=(new Date).getTime();var c=
new Image,b=Math.random();c.onload=function(){gEBMainWindow.EBP.ebBW._imageLoaded(a)};c.src=this._images[a].path+"?rnd="+b},_imageLoaded:function(a){this._images[a].end=(new Date).getTime();this._loaded++;this._loaded==this._images.length&&this._calculateSpeed()},listeners:[],addListener:function(a){this.listeners[gEBMainWindow.EBP.ebBW.listeners.length]=a},_dispatchEvent:function(){for(var a=0;a<this.listeners.length;a++)this.listeners[a]&&(this.listeners[a](),this.listeners[a]=null)},_calculateSpeed:function(){var a=
Math.min(this._images[0].end-this._images[0].start,this._images[1].end-this._images[1].start),c=this._images[2].end-this._images[2].start,b=c,d=this._images[2].bytes;c>a&&(b=c-a,d-=this._images[0].bytes);this.speed=Math.round(8*(d/(b/1E3)/1024))*this._adjustment;if(Infinity==this.speed||this.speed>=this._maxSpeed)this.speed=this._maxSpeed;else{for(a=0;a<this._tuneResults.length&&this.speed>this._tuneResults[a][0];a++);this.speed=Math.min(this._maxSpeed,Math.round(this.speed*this._tuneResults[a][1]))}this.checked=
!0;this.checking=!1;this._dispatchEvent()},init:function(){this.checking=!0;this._loadImage(0);this._loadImage(1);this._loadImage(2);var a=this;setTimeout(function(){if(!a.checked)a.speed=56,a.checked=!0,a.checking=!1,a._dispatchEvent()},5E3)}};function p(a){return function(){return a}}
(function(){function a(a){try{if(navigator.plugins&&navigator.plugins.length)for(var c=0;c<navigator.plugins.length;c++){var b=navigator.plugins[c];if(0<=b.name.indexOf(a))return b.name+(b.description?"|"+b.description:"")}}catch(d){}return""}function c(c){var o=new Date,y=new Date,u=[p("TF1"),p("015"),function(){return ScriptEngineMajorVersion()},function(){return ScriptEngineMinorVersion()},function(){return ScriptEngineBuildVersion()},function(){return f("{7790769C-0471-11D2-AF11-00C04FA35D02}")},
function(){return f("{89820200-ECBD-11CF-8B85-00AA005B4340}")},function(){return f("{283807B5-2C60-11D0-A31D-00AA00B92C03}")},function(){return f("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return f("{44BBA848-CC51-11CF-AAFA-00AA00B6015C}")},function(){return f("{9381D8F2-0288-11D0-9501-00AA00B911A5}")},function(){return f("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return f("{5A8D6EE0-3E18-11D0-821E-444553540000}")},function(){return f("{89820200-ECBD-11CF-8B85-00AA005B4383}")},
function(){return f("{08B0E5C0-4FCB-11CF-AAA5-00401C608555}")},function(){return f("{45EA75A0-A269-11D1-B5BF-0000F8051515}")},function(){return f("{DE5AED00-A4BF-11D1-9948-00C04F98BBC9}")},function(){return f("{22D6F312-B0F6-11D0-94AB-0080C74C7E95}")},function(){return f("{44BBA842-CC51-11CF-AAFA-00AA00B6015B}")},function(){return f("{3AF36230-A269-11D1-B5BF-0000F8051515}")},function(){return f("{44BBA840-CC51-11CF-AAFA-00AA00B6015C}")},function(){return f("{CC2A9BA0-3BDD-11D0-821E-444553540000}")},
function(){return f("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}")},function(){return eval("navigator.appCodeName")},function(){return eval("navigator.appName")},function(){return eval("navigator.appVersion")},function(){return g(["navigator.productSub","navigator.appMinorVersion"])},function(){return eval("navigator.browserLanguage")},function(){return eval("navigator.cookieEnabled")},function(){return g(["navigator.oscpu","navigator.cpuClass"])},function(){return eval("navigator.onLine")},function(){return eval("navigator.platform")},
function(){return eval("navigator.systemLanguage")},function(){return eval("navigator.userAgent")},function(){return g(["navigator.language","navigator.userLanguage"])},function(){return eval("document.defaultCharset")},function(){return eval("document.domain")},function(){return eval("screen.deviceXDPI")},function(){return eval("screen.deviceYDPI")},function(){return eval("screen.fontSmoothingEnabled")},function(){return eval("screen.updateInterval")},function(){return 0!==Math.abs(m-n)},function(){return d(o)},
p("@UTC@"),function(){var a=0,a=0;d(o)&&(a=Math.abs(m-n));return-(o.getTimezoneOffset()+a)/60},function(){return(new Date(2005,5,7,21,33,44,888)).toLocaleString()},function(){return eval("screen.width")},function(){return eval("screen.height")},function(){return k.Acrobat},function(){return k.Flash},function(){return k.QuickTime},function(){return k["Java Plug-in"]},function(){return k.Director},function(){return k.Office},p("@CT@"),function(){return m},function(){return n},function(){return o.toLocaleString()},
function(){return eval("screen.colorDepth")},function(){return eval("window.screen.availWidth")},function(){return eval("window.screen.availHeight")},function(){return eval("window.screen.availLeft")},function(){return eval("window.screen.availTop")},function(){return a("Acrobat")},function(){return a("Adobe SVG")},function(){return a("Authorware")},function(){return a("Citrix ICA")},function(){return a("Director")},function(){return a("Flash")},function(){return a("MapGuide")},function(){return a("MetaStream")},
function(){return a("PDFViewer")},function(){return a("QuickTime")},function(){return a("RealOne")},function(){return a("RealPlayer Enterprise")},function(){return a("RealPlayer Plugin")},function(){return a("Seagate Software Report")},function(){return a("Silverlight")},function(){return a("Windows Media")},function(){return a("iPIX")},function(){return a("nppdf.so")},function(){var a=document.createElement("span");a.innerHTML="&nbsp;";a.style.position="absolute";a.style.left="-9999px";document.body.appendChild(a);
var c=a.offsetHeight;document.body.removeChild(a);return c}];e();for(var j="",q=0;q<u.length;q++){c&&(j+=b(u[q].toString(),'"',"'",!0),j+="=");var r;try{r=u[q](this)}catch(h){r=""}j+=c?r:escape(r);j+=";";c&&(j+="\\n")}j=b(j,escape("@UTC@"),(new Date).getTime());j=b(j,escape("@CT@"),(new Date).getTime()-y.getTime());return window.f1b5?window.f1b5(j):j}function b(a,c,b,d){"boolean"!==typeof d&&(d=!1);for(var e=!0,f;0<=(f=a.indexOf(c))&&(d||e);)a=a.substr(0,f)+b+a.substr(f+c.length),e=!1;return a}function d(a){var c=
Math.min(m,n);return 0!==Math.abs(m-n)&&a.getTimezoneOffset()===c}function e(){for(var a="Acrobat,Flash,QuickTime,Java Plug-in,Director,Office".split(","),c=0;c<a.length;c++){var b=a[c],d=k,e=b,f=b,b="";try{if(navigator.plugins&&navigator.plugins.length)for(var g=RegExp(f+".* ([0-9._]+)"),f=0;f<navigator.plugins.length;f++){var h=g.exec(navigator.plugins[f].name);null===h&&(h=g.exec(navigator.plugins[f].description));h&&(b=h[1])}else if(window.ActiveXObject&&v[f])try{var l=new ActiveXObject(v[f][0]),
b=v[f][1](l)}catch(n){b=""}}catch(m){b=m.message}d[e]=b}}function g(a){for(var c=0;c<a.length;c++)try{var b=eval(a[c]);if(b)return b}catch(d){}return""}function f(a){var c="";try{"undefined"!==typeof h.a.getComponentVersion&&(c=h.a.getComponentVersion(a,"ComponentID"))}catch(b){a=b.message.length,c=escape(b.message.substr(0,40<a?40:a))}return c}function l(a){function c(a){d=d<<a[0]|a[1];for(e+=a[0];6<=e;)a=d>>e-6&63,b+=s.substring(a,a+1),e-=6,d^=a<<e}var b="",d=0,e=0;c([6,(a.length&7)<<3|0]);c([6,
a.length&56|1]);for(var f=0;f<a.length;f++){if(void 0==w[a.charCodeAt(f)])return;c(w[a.charCodeAt(f)])}c(w[0]);0<e&&c([6-e,0]);return b}var h={},m=(new Date(2005,0,15)).getTimezoneOffset(),n=(new Date(2005,6,15)).getTimezoneOffset(),k=[],v={Flash:["ShockwaveFlash.ShockwaveFlash",function(a){return a.getVariable("$version")}],Director:["SWCtl.SWCtl",function(a){return a.ShockwaveVersion("")}]};try{h.a=document.createElement("span"),"undefined"!==typeof h.a.addBehavior&&h.a.addBehavior("#default#clientCaps")}catch(z){}var k=
{},w={1:[4,15],110:[8,239],74:[8,238],57:[7,118],56:[7,117],71:[8,233],25:[8,232],101:[5,28],104:[7,111],4:[7,110],105:[6,54],5:[7,107],109:[7,106],103:[9,423],82:[9,422],26:[8,210],6:[7,104],46:[6,51],97:[6,50],111:[6,49],7:[7,97],45:[7,96],59:[5,23],15:[7,91],11:[8,181],72:[8,180],27:[8,179],28:[8,178],16:[7,88],88:[10,703],113:[11,1405],89:[12,2809],107:[13,5617],90:[14,11233],42:[15,22465],64:[16,44929],"0":[16,44928],81:[9,350],29:[8,174],118:[8,173],30:[8,172],98:[8,171],12:[8,170],99:[7,84],
117:[6,41],112:[6,40],102:[9,319],68:[9,318],31:[8,158],100:[7,78],84:[6,38],55:[6,37],17:[7,73],8:[7,72],9:[7,71],77:[7,70],18:[7,69],65:[7,68],48:[6,33],116:[6,32],10:[7,63],121:[8,125],78:[8,124],80:[7,61],69:[7,60],119:[7,59],13:[8,117],79:[8,116],19:[7,57],67:[7,56],114:[6,27],83:[6,26],115:[6,25],14:[6,24],122:[8,95],95:[8,94],76:[7,46],24:[7,45],37:[7,44],50:[5,10],51:[5,9],108:[6,17],22:[7,33],120:[8,65],66:[8,64],21:[7,31],106:[7,30],47:[6,14],53:[5,6],49:[5,5],86:[8,39],85:[8,38],23:[7,
18],75:[7,17],20:[7,16],2:[5,3],73:[8,23],43:[9,45],87:[9,44],70:[7,10],3:[6,4],52:[5,1],54:[5,0]},x="%20,;;;,%3B,%2C,und,fin,ed;,%28,%29,%3A,/53,ike,Web,0;,.0,e;,on,il,ck,01,in,Mo,fa,00,32,la,.1,ri,it,%u,le".split(","),s=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz";window.f1b5=function(a){for(var c=a,b=0;x[b];b++)c=c.split(x[b]).join(String.fromCharCode(b+1));c=l(c);if(void 0==c)return a;for(var b=65535,d=0;d<a.length;d++)b=(b>>>8|b<<8)&65535,b^=a.charCodeAt(d)&255,b^=(b&255)>>
4,b^=b<<12&65535,b^=(b&255)<<5&65535;b&=65535;a=""+s.charAt(b>>>12);a+=s.charAt(b>>>6&63);a+=s.charAt(b&63);return c+a};h.collect=function(a){try{if(!a)return c();var b;a:{var d;try{d=document.getElementById(a)}catch(e){}if(null===d||"undefined"===typeof d)try{d=document.getElementsByName(a)[0]}catch(f){}if(null===d||"undefined"===typeof d)for(var g=0;g<document.forms.length;g++)for(var h=document.forms[g],k=0;k<h.elements.length;k++){var l=h[k];if(l.name===a||l.id===a){b=l;break a}}b=d}if(null!==
b)try{b.value=c()}catch(m){b.value=escape(m.message)}}catch(n){}};window.fortyone=h;var t=navigator.userAgent.toLowerCase();"Gecko"===navigator.product&&2>=parseInt(t.substring(t.indexOf("rv:")+3,t.indexOf(")",t.indexOf("rv:")+3)).split(".")[0])&&window.fortyone.collect()})();EBPreServing.ResponseType={GET:0,POST:1};EBPreServing.ProvidersEnum=["AdTruth"];EBPreServing.UserIdProvider=function(){this._providers={};this._registerProviders()};
EBPreServing.UserIdProvider.prototype={_registerProviders:function(){this.registerProvider("AdTruth","ATData","fortyone.collect",!0)},registerProvider:function(a,c,b,d){if(this._providers[a])gEBMainWindow.EBP.log.warn(a+" provider already exist, provider not registered!");else{var e=this._verifyProviderCallbackFunc(b);e?(gEBMainWindow.EBP.log.info("Registering "+a+" provider"),this._providers[a]={tokenName:c,funcName:b,func:e,id:null,shouldCache:d}):gEBMainWindow.EBP.log.info("Could not resolve "+
a+" handler function name")}},_generateUserIds:function(a){for(var c=0;c<a.length;c++){var b=a[c],d=this._providers[b],e=null;if(d)if(!d.id||!d.shouldCache){gEBMainWindow.EBP.log.info("calculating ID with "+b);try{e=d.func.apply()}catch(g){e=null,gEBMainWindow.EBP.log.error("Got exception during "+b+" ID calculation: "+g)}d.id=e}else gEBMainWindow.EBP.log.info("Using "+b+" cached ID")}},getUserIds:function(a,c){var b="",b=this._getValidProviderNames(a);this._generateUserIds(b);return b=this._formatResponse(b,
c)},_formatResponse:function(a,c){var b="";switch(c){default:case EBPreServing.ResponseType.GET:for(var d=0;d<a.length;d++){var e=this._providers[a[d]];e.id&&(b+="&"+e.tokenName+"="+e.id)}case EBPreServing.ResponseType.POST:}return b},_verifyProviderCallbackFunc:function(a){for(var c=a.split("."),b=null,d=window,e=0,g=c.length;e<g;e++){var f=c[e];if(void 0!==d[f]&&(d=d[f],e==g-1&&"function"==typeof d)){gEBMainWindow.EBP.log.debug("Resolved function "+a);b=d;break}}return b},_getValidProviderNames:function(a){var c=
[];if("array"==EBP.Light.Infra.typeOf(a))for(var b=0;b<a.length;b++)EBP.Light.Infra.typeOf("number"==a[b])?c[c.length]=EBPreServing.ProvidersEnum[a[b]-1]:EBP.Light.Infra.typeOf("string"==a[b])&&(c[c.length]=EBP.Light.Infra.typeOf(a[b]));return c}};EBPreServing=window.EBPreServing||{};EBPreServing.ServingState={script:"SCRIPT",friendlyIframe:"FRIENDLY_IFRAME",unfriendlyIframe:"IFRAME"};
EBPreServing.SecretTags={gEbBAd:"gEbBAd",gEbAd:"gEbAd",gfEbForceStreaming:"gfEbForceStreaming",gEbEyeDivRefElement:"gEbEyeDivRefElement",gfEbUseCompression:"gfEbUseCompression",gfEbRemoveScroll:"gfEbRemoveScroll",gfEbUseMozHideIframe:"gfEbUseMozHideIframe",gnEbLowBWLimit:"gnEbLowBWLimit",gstrEbDisplayPos:"gstrEbDisplayPos",strPage:"strPage",gfEbChangeRelativeElements:"gfEbChangeRelativeElements",gfEbInlineBanner:"gfEbInlineBanner",gstrEbPreLoadScripts:"gstrEbPreLoadScripts",gfEbExpBanerIM:"gfEbExpBanerIM",
gstrEbIframeLocation:"gstrEbIframeLocation",gstrEbDomain:"gstrEbDomain",gnEbMinZIndex:"gnEbMinZIndex",gfEbCacheResources:"gfEbCacheResources",gfEbUseHTTPS:"gfEbUseHTTPS"};EBPreServing=window.EBPreServing||{};
EBPreServing.getTopWindow=function(){var a=window;a.EBservingMode=EBPreServing.ServingState.script;try{for(;a.self!==a.parent;){var c=null;try{c=a.parent.location.hostname}catch(b){}if(a.location.hostname===c)a=a.parent,a.EBservingMode=EBPreServing.ServingState.friendlyIframe;else{a.EBservingMode=EBPreServing.ServingState.unfriendlyIframe;break}}}catch(d){}return a};
EBPreServing._startEBPreservingFlow=function(){if(gEBMainWindow.EBP.downloadMgr)try{gEBMainWindow.EBP.downloadMgr._testFreedScript()}catch(a){gEBMainWindow.EBP.downloadMgr=new EBPreServing.DownloadManager}else gEBMainWindow.EBP.downloadMgr=new EBPreServing.DownloadManager;if(!gEBMainWindow.EBP.downloadMgr.ebSync.checkedIfPageLoaded)gEBMainWindow.EBP.downloadMgr.ebSync.checkedIfPageLoaded=!0,gEBMainWindow.EBP.downloadMgr.checkPageLoaded(gEBMainWindow,gEBMainWindow.EBP.downloadMgr.updatePageLoaded);
!gEBMainWindow.EBP.downloadMgr.ebSync.donwloadServerReq&&!gEBMainWindow.EBP.downloadMgr.ebSync.loadingCustomScript&&(gEBMainWindow.EBP.log.debug("Start serving request process"),gEBMainWindow.EBP.downloadMgr.initServerReq())};EBPreServing._addSecretTags=function(){var a=null,c;for(c in EBPreServing.SecretTags){var b=EBPreServing.SecretTags[c];b in window&&(a||(a={}),a[b]=window[b])}return a};
EBPreServing.DownloadManager=function(){gEBMainWindow.EBP.log.debug("DownloadManager.Constructor");if(!this.ebSync)this.ebSync={donwloadServerReq:!1,divId:0,currDoc:document,async:null,checkedIfPageLoaded:!1,loadingCustomScript:!1,placementIdObj:{}}};
EBPreServing.DownloadManager.prototype={ebSync:null,bigScriptObj:{},customScriptArr:[],initServerReq:function(){gEBMainWindow.EBP.log.startGroup("DownloadManager.initServerReq");try{var a=gEBMainWindow.EBP.ebTags[0];if(a)if("undefined"!=typeof a.sms&&""!=a.sms&&"/"!=a.sms[a.sms.length-1]&&(a.sms+="/"),this.ebSync.async=this.isAsyncMode(a),this.setAdditionalTagTokens(a),this.ebSync.placementIdObj[a.placementId]={},this.ebSync.placementIdObj[a.placementId].async=this.ebSync.async,a.bandWidth){var c=
this.handleBandwidthDetection(a);c||this.loadServerRequest()}else this.loadServerRequest();else gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - tag doesn't exist!!!");if(0<gEBMainWindow.EBP.ebTags.length&&!this.ebSync.donwloadServerReq&&!this.ebSync.loadingCustomScript&&!c){var b=this;setTimeout(function(){b.initServerReq()},0)}gEBMainWindow.EBP.log.endGroup()}catch(d){gEBMainWindow.EBP.log.exception("DownloadManager.initServerReq",d)}},loadServerRequest:function(){if(this.ebSync.loadingCustomScript){gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Currently loading custom script");
var a=this;this._customScriptServerRequestCallBack=function(){try{a.initServerReq()}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager._customScriptServerRequestCallBack",b)}}}else{this.ebSync.donwloadServerReq=!1;try{currTag=gEBMainWindow.EBP.ebTags.shift()}catch(c){0<gEBMainWindow.EBP.ebTags.length&&(currTag=gEBMainWindow.EBP.ebTags[0]);for(i=0;i<gEBMainWindow.EBP.ebTags.length-1;i++)gEBMainWindow.EBP.ebTags[i]=gEBMainWindow.EBP.ebTags[i+1];gEBMainWindow.EBP.ebTags.length--}currTag&&(this.setCurrTag(currTag),
this.handleCurrTag(currTag))}},handleCurrTag:function(a){this.ebSync.placementIdObj[a.placementId].async?(gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Start Async Client process"),this.handleAsyncTag(a)):(gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Start Sync Client process"),gEBMainWindow.EBservingMode===EBPreServing.ServingState.script&&a.loadInIframe?this.handleSyncTag(a):a.currDoc.write("<script src="+a.partialRequest+"><\/script>"))},setCurrTag:function(a){var c=
EBP.Light.Infra.getRandomNumber();a.ebRand=c;a.partialRequest+="&rand="+c;a.bandWidth&&gEBMainWindow.EBP.ebBW.checked&&56!=gEBMainWindow.EBP.ebBW.speed&&(a.partialRequest+="&BWVal="+(a.bwMult?a.bwMult*gEBMainWindow.EBP.ebBW.speed:gEBMainWindow.EBP.ebBW.speed)+"&BWDate=0");if(gEBMainWindow.EBservingMode&&gEBMainWindow.EBservingMode===EBPreServing.ServingState.unfriendlyIframe){if((c=EBP.Light.Infra.getAddInEyeDomain(gEBMainWindow,a.ebPtcl))&&""!=c)a.partialRequest+="&dm="+c;a.partialRequest=a.partialRequest.replace("ifrm=2",
"ifrm=1")}a.partialRequest+="&secCall=1";a.partialRequest=a.collectURL?a.partialRequest+"&vurl="+this.getVerificationUrl(a):a.partialRequest;a.partialRequest+=gEBMainWindow.EBP.UIdProviderMgr.getUserIds(a.uip,EBPreServing.ResponseType.GET);a.loadInIframe=a.lii?a.lii:!1},handleBandwidthDetection:function(a){var c=!1;if(!gEBMainWindow.EBP.ebBW)gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Create bandWidthDetector object (ebBW)"),gEBMainWindow.EBP.ebBW=new EBPreServing.BandWidthDetection;
if("undefined"!=typeof EBG&&"undefined"!=typeof EBG.BWDetection&&EBG.BWDetection.checked)gEBMainWindow.EBP.ebBW.speed=EBG.BWDetection.speed,gEBMainWindow.EBP.ebBW.checked=!0;if(!gEBMainWindow.EBP.ebBW.checked&&!gEBMainWindow.EBP.ebBW.checking){c="https:"==a.currDoc.location.protocol?"https://":"http://";a.ebPtcl="undefined"==typeof a.ebPtcl?c:a.ebPtcl;gEBMainWindow.EBP.ebBW.initImages(a.ebPtcl,a.sms);var b=this;gEBMainWindow.EBP.ebBW.addListener(function(){b.initServerReq()});gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Start Band Width detection");
gEBMainWindow.EBP.ebBW.init();c=!0}gEBMainWindow.EBP.ebBW.checking&&(gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Still detecting Band Width"),c=!0);return c},handleAsyncTag:function(a){this.ebSync.divId=a.containerId;gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Send Server Request");this._customScriptServerRequestCallBack=null;this.ebSync.donwloadServerReq=!0;var c={};c.currDoc=a.currDoc?a.currDoc:document;c.containerId=a.containerId;var b=this;this.scriptTag(a.partialRequest,
function(){b.ebSync.donwloadServerReq=!1;b.initServerReq()},c)},handleSyncTag:function(a){var c=this.setIfrmInRequest(a.partialRequest);if(c!==a.partialRequest&&c.length>a.partialRequest.length)a.partialRequest=c;c=EBP.Light.Infra.createFriendlyIframe(a.currDoc,a.ebRand,a.width,a.height);a.onLoadHandled=!1;var b={iframeContainer:c,myIfrmSrc:"<!DOCTYPE html><html><head></head><body><script type='text/javascript''>var inDapIF = true; "+this._translateSecretTags(a.tagsObj)+"<\/script><script src='"+
a.partialRequest+"'><\/script></body></html>",tag:a},a=a.currDoc.getElementById(a.containerId),b=this.bindTagToCallback(function(){if(!this.tag.onLoadHandled)EBP.Light.Infra.writeToFriendlyIframe(this.iframeContainer,this.myIfrmSrc,!0),this.tag.onLoadHandled=!0},b);EBP.Light.Infra.addChildToPage(c,a,"load",b)},bindTagToCallback:function(a,c){return a.bind?a.bind(c):function(a,c){return function(){return a.apply(c,arguments)}}(a,c)},_translateSecretTags:function(a){var c="",b;for(b in a)a.hasOwnProperty(b)&&
("object"!=typeof a[b]?c+="var "+this._getTagValue(b,a[b]):(c+=" var "+b+" =  new Object();",c+=this._stringnifyObj(b,a[b],"")));return c},_stringnifyObj:function(a,c,b){var d="",e;for(e in c)c.hasOwnProperty(e)&&(d=a+"."+e,"object"!=typeof c[e]?b+=this._getTagValue(d,c[e]):(b+=d+"= new Object();",b=this._stringnifyObj(d,c[e],b)));return b},_getTagValue:function(a,c){return"string"==typeof c?a+" = unescape('"+escape(c)+"');":a+" ="+c+";"},setIfrmInRequest:function(a){var c=a.indexOf("&ifrm");if(-1!=
c){if(-1==a.indexOf("&ifrm=-1"))var b="",b=a.substr(0,c),a=b=b+"&ifrm=-1"+currTag.partialRequest.substr(c+7,a.length)}else a+="&ifrm=-1";return a},setAdditionalTagTokens:function(a){if("undefined"==typeof a.placementId){var c=a.partialRequest.split("&");requestObj={};for(var b=1;b<c.length;b++)c[b]=c[b].split("="),requestObj[[c[b][0]]]=c[b][1];a.placementId=requestObj.pli;a.width=requestObj.w;a.height=requestObj.h}},getVerificationUrl:function(a){try{var c="";"undefined"!=typeof a.vurl&&""!=a.vurl?
c=a.vurl:(a=gEBMainWindow,c=a.EBservingMode==EBPreServing.ServingState.unfriendlyIframe?a.document.referrer:a.location.href);return c=escape(c)}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager.getUrl",b)}},isAsyncMode:function(a){gEBMainWindow.EBP.log.debug("DownloadManager.isAsyncMode ");try{return a.asyncMode||a.bandWidth}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager.isAsyncMode",c)}},reportImg:function(a){gEBMainWindow.EBP.log.debug("DownloadManager.reportImg ");try{(new Image).src=
a}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager.reportImg",c)}},scriptTag:function(a,c,b){gEBMainWindow.EBP.log.startGroup("DownloadManager.scriptTag");try{var d=b&&b.currDoc?b.currDoc:document,e=EBP.Light.Infra.createScriptElement(d,"script","text/"+(a.type||"javascript"),a.src||a);e.onreadystatechange=e.onload=function(){var a=e.readyState;if("function"==typeof c&&!c.done&&(!a||/loaded|complete/.test(a)))c.done=!0,c(b)};d=b&&b.currDoc?b.currDoc:document;if(!b||!b.containerId)EBP.Light.Infra.addScriptElement(e);
else{var g=d.getElementById(b.containerId);EBP.Light.Infra.addScriptElement(e,g)}gEBMainWindow.EBP.log.endGroup()}catch(f){gEBMainWindow.EBP.log.exception("DownloadManager.scriptTag",f)}},checkPageLoaded:function(a,c){gEBMainWindow.EBP.log.startGroup("DownloadManager.checkPageLoaded");try{var b=!1,d=!0,e=a.document,g=e.documentElement,f=e.addEventListener?"addEventListener":"attachEvent",l=e.addEventListener?"removeEventListener":"detachEvent",h=e.addEventListener?"":"on";gEBMainWindow.EBP.init=function(d){if(!("readystatechange"==
d.type&&"complete"!=e.readyState)&&(("load"==d.type?a:e)[l](h+d.type,gEBMainWindow.EBP.init,!1),!b&&(b=!0)))c.call(a,d.type||d)};gEBMainWindow.EBP.poll=function(){try{g.doScroll("left")}catch(a){setTimeout(gEBMainWindow.EBP.poll,50);return}gEBMainWindow.EBP.init("gEBMainWindow.EBP.poll")};if("complete"==e.readyState)c.call(a,"lazy");else{if(e.createEventObject&&g.doScroll){try{d=!a.frameElement}catch(m){}d&&gEBMainWindow.EBP.poll()}e[f](h+"DOMContentLoaded",gEBMainWindow.EBP.init,!1);e[f](h+"readystatechange",
gEBMainWindow.EBP.init,!1);a[f](h+"load",gEBMainWindow.EBP.init,!1)}gEBMainWindow.EBP.log.endGroup()}catch(n){gEBMainWindow.EBP.log.exception("DownloadManager.checkPageLoaded",n)}},updatePageLoaded:function(){gEBMainWindow.EBP.log.debug("DownloadManager.isPageLoaded");try{gEBMainWindow.EBP.isPageLoaded=!0}catch(a){gEBMainWindow.EBP.log.exception("DownloadManager.isPageLoaded",a)}},loadBigScript:function(a,c,b,d){gEBMainWindow.EBP.log.startGroup("DownloadManager.loadBigScript");try{if(window.gstrAdPrefix){var e=
window.gstrAdPrefix;-1==c.indexOf(e)&&(c=c.replace(/Ad_/,e))}if(this.ebSync.loadingCustomScript){gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: loading cutom script: {0} ",b);var g=this;this._customScriptBigScriptCallBack=function(){try{g.loadBigScript(a,c,b,d),"function"==typeof g._customScriptServerRequestCallBack&&g._customScriptServerRequestCallBack()}catch(e){gEBMainWindow.EBP.log.exception("DownloadManager._customScriptBigScriptCallBack"+e)}}}else{this._customScriptBigScriptCallBack=
null;gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: loading {0} script",b);var f={};f.containerId=a?a:null;f.bigScriptSrc=c?c:null;f.scriptName=b?b:null;f.currDoc=d?d:document;e={containerId:a,currDoc:d};this.bigScriptObj[b]=this.bigScriptObj[b]||{};this.bigScriptObj[b].waitingToLoad=this.bigScriptObj[b].waitingToLoad||[];-1==this.indexOfArray(this.bigScriptObj[b].waitingToLoad,e)&&this.bigScriptObj[b].waitingToLoad.push(e);this.bigScriptObj[b].downloaded="undefined"!=typeof this.bigScriptObj[b].downloaded?
this.bigScriptObj[b].downloaded:!1;this.bigScriptObj[b].isFirst="undefined"!=typeof this.bigScriptObj[b].isFirst?this.bigScriptObj[b].isFirst:!0;this.bigScriptObj&&this.bigScriptObj[b]&&this.bigScriptObj[b].isFirst?(gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: First time loading {0} script",this.bigScriptObj[b]),this.bigScriptObj[f.scriptName].waitingToLoad.shift(),this.bigScriptObj[f.scriptName].isFirst=!1,g=this,this.scriptTag(c,function(){g._releaseWaitingRequests(f)},f)):(gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: Script {0} was already downloaded",
this.bigScriptObj[b]),this.bigScriptObj[b].downloaded&&this._releaseWaitingRequests(f));gEBMainWindow.EBP.log.endGroup()}}catch(l){gEBMainWindow.EBP.log.exception("DownloadManager.loadBigScript",l)}},indexOfArray:function(a,c){gEBMainWindow.EBP.log.debug("DownloadManager.indexOfArrays");try{for(var b=0;b<a.length;b++)if(a[b]==c)return b;return-1}catch(d){gEBMainWindow.EBP.log.exception("DownloadManager.indexOfArray",d)}},loadCustomScript:function(a,c){gEBMainWindow.EBP.log.startGroup("DownloadManager.loadCustomScript");
try{var b={};b.currDoc="undefined"!=typeof c?c:document;if(0!=this.ebSync.divId)b.containerId=this.ebSync.divId;if("undefined"!=typeof a){for(var d=a.length-1;0<=d;d--)if(""==a[d]||"http://"==a[d].substr(0,7)&&"https://"==ebPtcl)gEBMainWindow.EBP.log.info("custom script "+a[d]+" will not be loaded since it is from not secured protocol while the ad runs from secured protocol"),a.splice(d,1);if(0<a.length)this.ebSync.loadingCustomScript=!0;b.CSArray=a;for(d=0;d<a.length;d++)"http"!=a[d].substr(0,4)&&
(a[d]=ebResourcePath+"CustomScripts/"+a[d]),this.customScriptArr[d]={},this.customScriptArr[d].cs=a[d],this.customScriptArr[d].loaded=!1;this.customScriptsLoader(b)}gEBMainWindow.EBP.log.endGroup()}catch(e){gEBMainWindow.EBP.log.exception("DownloadManager.loadCustomScript",e)}},customScriptsLoader:function(a){gEBMainWindow.EBP.log.startGroup("DownloadManager.customScriptsLoader");try{if("undefined"!=typeof a&&a.CSArray&&0<a.CSArray.length){var c=a.CSArray.pop();a.index=a.CSArray.length;var b=this,
d=parseInt(a.index);gEBMainWindow.EBP.log.debug("DownloadManager.customScriptsLoader - loading script # :  {0}",c);this.scriptTag(c,function(){b.handleCustomScriptsLoaded(a,d)},a);this.customScriptsLoader(a)}gEBMainWindow.EBP.log.endGroup()}catch(e){gEBMainWindow.EBP.log.exception("DownloadManager.customScriptsLoader",e)}},handleCustomScriptsLoaded:function(a,c){gEBMainWindow.EBP.log.startGroup("DownloadManager.handleCustomScriptsLoaded");try{if(this.customScriptArr&&this.customScriptArr[c])this.customScriptArr[c].loaded=
!0;if(this.areAllCustomScriptsLoaded())this.ebSync.loadingCustomScript=!1,"function"==typeof this._customScriptBigScriptCallBack&&this._customScriptBigScriptCallBack()}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager.handleCustomScriptsLoaded",b)}},areAllCustomScriptsLoaded:function(){gEBMainWindow.EBP.log.debug("DownloadManager.areAllCustomScriptsLoaded");try{if(this.customScriptArr){for(var a=0;a<this.customScriptArr.length;a++)if(!this.customScriptArr[a].loaded)return!1;return!0}}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager.areAllCustomScriptsLoaded",
c)}},_customScriptBigScriptCallBack:null,_customScriptServerRequestCallBack:null,_releaseWaitingRequests:function(a){gEBMainWindow.EBP.log.startGroup("DownloadManager._releaseWaitingRequests");try{if("object"==typeof a&&"undefined"!=typeof a.scriptName&&(this.bigScriptObj[a.scriptName].downloaded=!0,this.bigScriptObj[a.scriptName]))for(;0<this.bigScriptObj[a.scriptName].waitingToLoad.length;){var c=this.bigScriptObj[a.scriptName].waitingToLoad.shift();gEBMainWindow.EBP.log.debug("Big script will be loaded into containderId {0}",
c.containerId);a.containerId=c.containerId;a.currDoc=c.currDoc;this.scriptTag(a.bigScriptSrc,function(){},a)}gEBMainWindow.EBP.log.endGroup()}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager._releaseWaitingRequests",b)}},_testFreedScript:function(){return window&&Array?!0:!1}};gEBMainWindow=window.gEBMainWindow||EBPreServing.getTopWindow();gEBMainWindow.EBP=gEBMainWindow.EBP||{};gEBMainWindow.EBP.log=new EBP.Light.Logger(EBP.Light.Infra.getUrlParameter(EBP.Light.Logger.DebugMode)||0);
gEBMainWindow.EBP.UIdProviderMgr=gEBMainWindow.EBP.UIdProviderMgr||new EBPreServing.UserIdProvider;gEBMainWindow.EBP.ebTags=gEBMainWindow.EBP.ebTags||[];if(void 0!==window.ebNewTagArr)for(var i=0;i<ebNewTagArr.length;i++)if("undefined"==typeof ebNewTagArr[i].collected){ebNewTagArr[i].currDoc=document;ebNewTagArr[i].collected=!0;var tags=EBPreServing._addSecretTags();if(null!=tags)ebNewTagArr[i].tagsObj=tags;gEBMainWindow.EBP.ebTags[gEBMainWindow.EBP.ebTags.length]=ebNewTagArr[i]}
if(void 0!==window.ebNewTag&&"undefined"==typeof ebNewTag.collected){ebNewTag.currDoc=document;ebNewTag.collected=!0;tags=EBPreServing._addSecretTags();if(null!=tags)ebNewTag.tagsObj=tags;gEBMainWindow.EBP.ebTags[gEBMainWindow.EBP.ebTags.length]=ebNewTag}gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - gEBMainWindow location:  {0}",gEBMainWindow.location.href);gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - curr document location:  {0}",document.location.href);
0<gEBMainWindow.EBP.ebTags.length&&EBPreServing._startEBPreservingFlow();
