(function(z){
var tG=function(a,b,c){b=(b||a.Nd)===z.Fr.vd;return c?(a=a.g.v.B().get(z.U.wr),b?-1:-a):a.kp+(b?-1:1)};var uG=function(a){z.vr.call(this,a);this.kp=0;this.Nd=z.Fr.vd};var vG=function(a,b,c,d){a=a.ui[b];var f=a[c];a[c]=function(a){f(a);d(a)}};var wG=function(a,b){var c=a.Qb.jt(b),d=new z.rr;d.bz=function(a){return(0,z.ke)(a,function(a){return a.content.ancestorId==b.id})};a.Qb.gj(c,d);return d};var xG=function(a,b){a.Y_=b};var yG=function(a,b,c){vG(a,b,z.vu,c)};var zG=function(a,b,c){vG(a,b,z.wu,c)};
var AG=function(a){return'\x3ca href\x3d"'+(0,z.Kl)(a.Oa)+'" title\x3d"'+(0,z.S)(a.da)+'" data-id\x3d"'+a.id+'" class\x3d"fyre-follower fyre-follower-'+a.uX+'"\x3e\x3cimg src\x3d"'+(0,z.Kl)(a.Bc)+'" alt\x3d"'+(0,z.S)(a.da)+'" onerror\x3d"javascript:this.src\x3d\''+(0,z.S)(a.Vb)+"';\" /\x3e\x3c/a\x3e"};
var BG=function(a){return(0,z.Ro)(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3\x3e\x3cstrong\x3e\x3c/strong\x3e'+(0,z.S)(a.l.WR)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.S)(a.l.UA)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(a.l.Uq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+(0,z.S)(a.l.WA)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e"};
var CG=function(a){return'\x3cdiv class\x3d"fyre '+(a.Rd?"fyre-liveblog ":"")+(a.Xh?"fyre-livechat ":"")+(a.GX?"fyre-bootstrap":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.qb?"fyre-avatar-disabled":"")+'"\x3e'+(a.Ly?(0,z.Io)(a):"")+'\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.qb?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.hq?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'};var DG=function(a){return'\x3cdiv class\x3d"tooltip"\x3e'+(0,z.S)(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e'};var EG=function(a){var b=z.gq,c=new z.Hj(a.content);c.set(b.ta,a.Hl);return c};var FG=function(){};var GG=function(a,b){z.Yi.call(this,b,a)};var HG=function(a,b){z.Ou.call(this,a,b)};
var IG=function(a,b,c){var d=a.g.Qb;d.ui[c]&&(zG(d,c,(0,z.s)(function(a){b.f(a,"sortBackTo",this.EK)},a)),yG(d,c,(0,z.s)(function(a){b.ib(a,"sortBackTo",this.EK)})))};var JG=function(a,b){var c=a.g.Qb;c.ui[4]&&(zG(c,4,(0,z.s)(function(a){b.f(a,"threadBreakout",this.Et)},a)),yG(c,4,(0,z.s)(function(a){b.ib(a,"threadBreakout",this.Et)})))};var KG=function(a,b){var c=[a.Xn,a.mC];a.Wn&&c.push(a.Wn);a.ov&&c.push(a.ov);a.nC&&c.push(a.nC);(0,z.w)(c,function(a){(0,z.We)(a,LG.cx)});(0,z.K)(b,LG.cx)};
var MG=function(a,b,c){b&&NG(a,c);(0,z.Zh)(a.pN,"display",b?"none":"block");(0,z.Zh)(a.Wn,"display",b?"block":"none")};var NG=function(a,b){var c=a.Xn,d=a.rp,f=z.W.get(z.W.e.mD);4===b&&(c=a.ov,d=a.$I,f=z.W.get(z.W.e.nD));a.Wn.innerHTML=f;a.p().tj(a.Wn,"click",(0,z.s)(function(a){a.stopPropagation();MG(this,!1);KG(this,c);d.apply(this)},a))};var OG=function(a,b){z.Ou.call(this,a,b)};var PG=function(a,b){z.Nt.call(this,a,b);this.fe=!1;this.Ya=new z.Vt;this.Ya.yc(this);this.$w="archiveShowMore"};
var QG=function(a,b){z.Mu.call(this,a,b)};var RG=function(a,b,c){z.Kp.call(this,a,b,c);this.GC=b||"";this.Ue(DG(this.r()))};var SG=function(a,b,c){z.Ep.call(this,a,b||3,c)};var TG=function(a,b){z.T.call(this,b);this.k=a};var UG=function(a,b){z.T.call(this,b);this.kd=a};var VG=function(a,b){UG.call(this,a,b)};var WG=function(a,b,c,d,f){z.Nu.call(this,a,b,c,d,f)};
var XG=function(a,b){z.Vu.call(this,a,b);var c=a.v.Xc(),d=a.v.B();this.Af=new WG(a,c,a.rq.je,d.Xh()||z.Zb);this.P(this.Af);a.pa.qb||(this.Ap=new VG(c),this.P(this.Ap));this.It=new z.Lu;this.P(this.It)};var YG=function(a,b,c){var d=a.g.Qb;a.dispatchEvent({type:"threadBreakout",yv:b,Rb:(0,z.s)(function(){MG(this.si,!0);d.Ym(5).Th(b,c,!0)},a),Ok:(0,z.s)(function(){MG(this.si,!0);var a=d.Ym(5);(0,z.Lt)(a)},a)})};var ZG=function(a){z.Au.call(this,a);this.Oo=1};
var $G=function(a){z.Lo.call(this,a);(0,z.Xq)(a.v);this.Nc=new XG(a);this.$s.start();this.mn(this.Nc);(0,z.Oo)(this)};var aH=function(a){this.zH=GG;this.$N=$G;z.W.Xq(a.strings||{});z.fj.call(this,a)};var bH=function(a){a.Il&&(a.Il.q(),delete a.Il)};(0,z.u)(uG,z.vr);uG.prototype.Um=(0,z.ea)(2);uG.prototype.kK=(0,z.ea)(34);uG.prototype.lK=(0,z.ea)(13);uG.prototype.kK=(0,z.kd)(34,function(a){this.Wa||(this.Eq[a]=!1,(0,z.wr)(this,a,function(a){a.M(a.D.Io)}))});
z.Po.prototype.hj=(0,z.kd)(26,function(a,b,c){a=(0,z.va)("%s%scollection/%s/hot/",z.v.N.Xd,z.v.Jf,a.qa);(new z.Uk({url:a,va:b,ra:c})).send()});z.Qr.prototype.hj=(0,z.kd)(25,function(a){var b={qa:this.g.v.B().id},c=z.Po.F().hj;(0,z.Rr)(this,c,b,a);return a});z.eA.prototype.hj=(0,z.kd)(24,function(){(0,z.Vr)(this);this.Sj=new z.Qr(this.t,void 0);var a=new z.rr;this.Sj.hj(a);return a});z.T.prototype.rL=(0,z.kd)(20,(0,z.e)("ca"));z.Vi.prototype.hq=(0,z.kd)(15,function(){return this.get(this.d.vr)});
uG.prototype.lK=(0,z.kd)(13,function(a,b){if(!this.Wa){var c=this.g.v.B(),d=(0,z.Jq)(a,b);c.set(z.U.wr,d.BY);(0,z.A)(d.nb,(0,z.s)(this.g.J.M,this.g.J,"bootstrap_author_received"));(0,z.A)(d.content,function(a){(0,z.cb)(d.content,(0,z.xr)(this,a))},this);(0,z.cb)(this.rd,(0,z.je)(d.content,(0,z.eb)(a)));this.Rf(a,d.content);(0,z.wr)(this,a,function(b){b.M(b.D.hm,{Pe:a});b.set(b.d.zg,!0)})}});
z.Po.prototype.ej=(0,z.kd)(7,function(a,b,c){a=(0,z.va)("%s%scollection/%s/top/%s/",z.v.N.Xd,z.v.Jf,a.qa,a.QR);(new z.Uk({url:a,va:b,ra:c})).send({format:"stream"})});z.Qr.prototype.ej=(0,z.kd)(6,function(a,b){var c={qa:this.g.v.B().id,QR:a},d=z.Po.F().ej;(0,z.Rr)(this,d,c,b);return b});z.eA.prototype.ej=(0,z.kd)(5,function(a){(0,z.Vr)(this);this.Sj=new z.Qr(this.t,void 0);var b=new z.rr;this.Sj.ej(a,b);return b});
uG.prototype.Um=(0,z.kd)(2,function(a,b){this.kp=a;this.Nd=b||this.Nd;var c=this.ke[a]=new z.rr;z.Po.F();var d=this.g.v.B(),f=(0,z.s)(this.lK,this,a),g=(0,z.s)(this.kK,this,a),h=d.get(z.U.hd),d=z.v.Zx(h,d.id)+String(a)+".json";(0,z.Qo)(0,d,f,g);return c});z.eA.prototype.Um=(0,z.kd)(1,function(a,b){this.xm||(this.xm=new uG(this.t));var c=this.xm,d=tG(c,a,b);return c.Um(d,a)});var cH={sR:0,NONE:1,lm:2,wo:3};(0,z.u)(FG,z.lj);(0,z.Ie)(FG);
FG.prototype.eL=function(a){var b={};b.Ri=a[z.rA.fD];var c=a[z.rA.jD];c&&(b.$R=c);if(c=a[z.rA.kD]||z.Zb&&(0,z.ha)(z.fyre.sp))b.GH=c;b.Yx=a[z.rA.V0]?!0:!1;c=a[z.rA.qm];b.wh=c?c:!1;if(c=a[z.rA.ED])b.la=c;if(c=a[z.rA.wg])b.xk=c;if(c=a[z.rA.KD])b.oy=c;b.De=(0,z.mj)(this,a[z.rA.QD]);if(c=a[z.rA.$D])b.Km=c;if(c=a[z.rA.ZF])b.jg=c;if(c=a[z.rA.qG])b.bC=c;c=a[z.rA.zG];null!=c&&(b.iC=c);if(c=a[z.rA.TD]||!1)b.qb=c;b.readOnly=a[z.rA.READ_ONLY]||!1;if(c=a[z.rA.eH])b.VN=c;if(c=a[z.rA.hD])b.Rx=c;if(c=a[z.rA.oo])b.$i=
c;b.Td=a[z.rA.hd];b.Qy=(0,z.nj)(a[z.rA.bD]);return b};(0,z.u)(GG,z.Yi);GG.prototype.$B=function(a){this.Bl=new z.Bq(this);this.Fx=new z.oq(this,a);this.Kb=new z.gl(this);this.ya=new z.er(this,a);this.rq=new z.kr(this);this.v=new z.Tq(this,a);this.tb=new z.eA(this,a);this.bY=new z.uk;this.cr=new z.gs(this,a);this.JL=new z.mr(this);this.Qb=new z.qu(this)};(0,z.u)(HG,z.Ou);var LG={wO:"fyre-stream-sort-back",Pl:"fyre-content-loading",tP:"fyre-follow-conversation",UQ:"fyre-stream-sort-hot-threads",VQ:"fyre-stream-sort-top-comments",HG:"fyre-stream-sort-newest",IG:"fyre-stream-sort-oldest",cx:"fyre-stream-sort-selected",JG:"fyre-stream-sort-options"};z.m=HG.prototype;
z.m.r=function(){var a={},b=this.g.v,c=b.B();a.LA=b.B().Rd();a.zY=!z.R.get(z.R.d.Fb);a.al=b.al(z.R.id);a.cT=c.get(z.U.mm)===cH.lm;a.bT=c.get(z.U.mm)===cH.wo;a.l={XX:z.W.get(z.W.e.Kr),$X:z.W.get(z.W.e.Lr),sX:z.W.get(z.W.e.wo),UA:z.W.get(z.W.e.jk),WA:z.W.get(z.W.e.kk),Uq:z.W.get(z.W.e.dx),kr:z.W.get(z.W.e.Lo),j0:z.W.get(z.W.e.lm)};return a};
z.m.G=function(a){HG.b.G.call(this,a);a=this.c;var b;b=this.r();b=(0,z.Ro)(b)+(b.LA?'\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.zY?b.al?(0,z.S)(b.l.$X):(0,z.S)(b.l.XX):"")+"\x3c/a\x3e":"")+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.S)(b.l.UA)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(b.l.Uq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
(0,z.S)(b.l.WA)+"\x3c/a\x3e"+(b.cT?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(b.l.Uq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+(0,z.S)(b.l.j0)+"\x3c/a\x3e":"")+(b.bT?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.S)(b.l.Uq)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+(0,z.S)(b.l.sX)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e';a.innerHTML=b;this.Tm=this.n(LG.tP);this.ov=this.n(LG.UQ)||
null;this.nC=this.n(LG.VQ)||null;this.Wn=this.n(LG.wO);this.Xn=this.n(LG.HG);this.mC=this.n(LG.IG);this.pN=this.n(LG.JG);this.oc=this.n(LG.Pl);this.Cd()};z.m.m=function(){HG.b.m.call(this);var a=this.p();z.R.on(z.R.D.ed,this.nj,this);a.f(this.c,"click",this.zb);(0,z.w)([3,4,5],function(b){IG(this,a,b)},this);JG(this,a)};
z.m.zb=function(a){a.preventDefault();a=a.target;if(!(0,z.$e)(a,LG.cx)&&"A"===a.tagName&&a!==this.Wn)if(a===this.Tm)this.jK();else switch(KG(this,a),this.og(),a){case this.ov:this.$I();break;case this.nC:this.dispatchEvent({type:"sortTopComments",Rb:(0,z.s)(this.Cd,this)});break;case this.Xn:this.rp(z.Fr.vd);break;case this.mC:this.rp(z.Fr.Sr)}};z.m.EK=function(a){a.stopPropagation();MG(this,!1);KG(this,this.Xn);this.rp()};
z.m.Et=function(a){var b=a.Rb;(0,z.cb)(a,{Rb:(0,z.s)(function(){b();MG(this,!0,4)},this)})};z.m.rp=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||z.Fr.vd,Rb:(0,z.s)(this.Cd,this)})};z.m.$I=function(){this.dispatchEvent({type:"sortHotThreads",Rb:(0,z.s)(this.Cd,this)})};z.m.jK=function(){var a=this.g.v;a.B();var b=z.R.d;z.R.id?(b=a.al(z.R.get(b.Q)),a.ht(!b),a=b?z.W.get(z.W.e.Kr):z.W.get(z.W.e.Lr),this.Tm.innerHTML=a):(0,z.il)(this.g.Kb,(0,z.s)(this.jK,this))};
z.m.nj=function(){var a=this.g.v,b=a.B(),c=z.R.d,b=!b.Rd()||z.R.get(c.Fb);this.Tm&&(b?(0,z.L)(this.Tm,!1):(a=a.al(z.R.id)?z.W.get(z.W.e.Lr):z.W.get(z.W.e.Kr),this.Tm.innerHTML=a,(0,z.L)(this.Tm,!0)))};z.m.j=function(){HG.b.j.call(this);z.R.off(null,null,this)};(0,z.u)(OG,HG);OG.prototype.G=function(a){this.c=a;(0,z.Bl)(a,BG,this.r());this.Xn=this.n(LG.HG);this.mC=this.n(LG.IG);this.pN=this.n(LG.JG);this.oc=this.n(LG.Pl);this.Cd()};OG.prototype.rp=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",eh:this.Y_.eh,direction:a,Rb:(0,z.s)(this.Cd,this)})};OG.prototype.r=function(){return{l:{WR:z.W.get(z.W.e.dD),UA:z.W.get(z.W.e.jk),WA:z.W.get(z.W.e.kk),Uq:z.W.get(z.W.e.dx),kr:z.W.get(z.W.e.Lo)}}};(0,z.u)(PG,z.Nt);var dH={Cb:"fyre-stream-content",Of:"fyre-stream-more"};z.m=PG.prototype;z.m.Zo=function(a){this.clear();(0,z.L)(this.c,!0);this.Nd=a};z.m.clear=function(){this.Vf.Ef();this.gc={};this.hn=[];this.xi=this.Am=null;for(this.oC=[];this.xa&&0!=this.xa.length;)this.Kq(0).q()};z.m.G=function(a){PG.b.G.call(this,a);(0,z.Bl)(this.c,z.So,this.r());this.Al=this.n(dH.Cb);this.Lj=this.n(dH.Of);this.Ya.O(this.Lj);(0,z.L)(this.Lj,!1)};z.m.j=function(){this.Ya&&this.Ya.q();this.Ya=null;PG.b.j.call(this)};
z.m.m=function(){PG.b.m.call(this);this.p().f(this.Ya,"showMore",this.cA)};z.m.r=function(){return{Dg:z.v.N.sb,aJ:!!this.Ya,l:{eC:z.W.get(z.W.e.eD)}}};z.m.dA=function(){this.Ya.jv()};z.m.qB=function(){this.dispatchEvent({type:this.$w,direction:this.Nd,target:this,Rb:(0,z.s)(this.dA,this),Ok:(0,z.s)(this.GK,this)})};z.m.br=function(){var a=this.t.tb.xm,b=this.Nd,c=a.g.v.B(),b=b===z.Fr.Sr,c=c.get(z.U.wr),c=!b&&a.kp>-c;b&&-1>a.kp||c?this.Ya.show():this.Ya.wa()};
z.m.start=function(){this.fe||(this.qB(),this.fe=!0)};(0,z.u)(QG,z.Mu);QG.prototype.r=function(){var a=this.k.get(z.U.ve),b;b=this.k.Rd()?{gp:z.W.get(z.W.e.ww),Gs:z.W.get(z.W.e.oF)}:{gp:z.W.get(z.W.e.Nl),Gs:z.W.get(z.W.e.te)};return{su:a,l:b}};QG.prototype.QC=function(){var a=this.c,b=this.r(),c="\x3cspan\x3e";switch(b.su){case 1:c+="1 "+(0,z.S)(b.l.Gs);break;default:c+=(0,z.S)(b.su)+" "+(0,z.S)(b.l.gp)}a.innerHTML=c+"\x3c/span\x3e"};(0,z.u)(RG,z.Kp);RG.prototype.dr=200;RG.prototype.ij=function(){return new SG(this.jd)};RG.prototype.r=function(){var a={};a.message=this.GC;return a};(0,z.u)(SG,z.Ep);
SG.prototype.Pb=function(a,b,c){var d=(0,z.Bi)(this.element),d=new z.cf(d.width,d.height+25);b=(0,z.Bp)(this.element,this.Ui,a,b,d,c,9);(0,z.fi)(a.lastChild,0);b&&(d=new z.cf(0,-5),(0,z.Bp)(this.element,2,a,1,d,c,5),(0,z.fi)(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};(0,z.u)(TG,z.T);z.m=TG.prototype;z.m.o=function(){this.c=(0,z.Gl)(AG,this.r())};z.m.m=function(){TG.b.m.call(this);this.eb=new RG(this.c,this.k.get(z.M.$));this.p().f(this.c,"click",this.zb)};z.m.j=function(){TG.b.j.call(this);this.eb&&this.eb.q()};z.m.r=function(){var a={};a.Bc=this.k.get(z.M.Pa);a.Vb=this.k.get(z.M.Yj);a.da=this.k.get(z.M.$);a.id=this.k.id;a.uX=this.k.id.replace(/[@.]/g,"-");a.Oa=this.k.get(z.M.Gb);return a};
z.m.zb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({w:this.k,type:"author_click"})};(0,z.u)(UG,z.T);z.m=UG.prototype;z.m.Co=10;z.m.j=function(){UG.b.j.call(this);delete this.kd};z.m.R=function(){UG.b.R.call(this);this.kd.off(null,null,this)};z.m.RJ=function(a){a=new TG(a);var b=this.Ge();if(b===this.Co){var c=this.Kq(b-1);c&&(c.q(),b--)}0<b?this.Ae(a,0,!0):this.P(a,!0)};z.m.sW=function(a){var b;this.ld(function(c){a.id===c.k.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.m.lj=function(){this.kd.on(this.kd.D.Ze,this.RJ,this);this.kd.on(this.kd.D.Id,this.sW,this);var a=this.kd.vc.reverse().slice(0,this.Co);(0,z.w)(a,this.RJ,this)};(0,z.u)(VG,UG);(0,z.u)(WG,z.Nu);WG.prototype.G=function(a){WG.b.G.call(this,a);this.rl()};WG.prototype.rl=function(){this.c.innerHTML=(0,z.Xo)(this.r())};(function(a,b){function c(){var a=F.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){F.A_||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,function(a){b[a]=d(a);g.createElement(a);
return'c("'+a+'")'})+");return n}")(F,g)}function f(a){var b;if(a.gT)return a;if(F.z_&&!n){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";b=!!c.insertBefore(b.lastChild,
c.firstChild)}r||(b=!d(a));b&&(a.gT=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,n,r;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(n="hidden"in c)&&"function"==typeof a.DX&&a.DX("#modernizr{}",function(b){b.hidden=!0;n="none"==(a.getComputedStyle?
a.getComputedStyle(b,null):b.currentStyle).display});r=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var F={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==g.z_,shivMethods:!1!==
g.A_,type:"default",shivDocument:f};f(b)})(z.t.window,z.t.document);(0,z.u)(XG,z.Vu);XG.prototype.Ru=function(a,b){if(!this.Wa){this.L=b;var c=b.get(z.U.mh),d=b.get(z.U.xe);this.Jv=new z.Su(c,d,a.pa.qb);this.P(this.Jv);this.Hs=new QG(a.v.B());this.P(this.Hs);this.ru=null;b.hq()&&(this.Qx=new OG(a),this.P(this.Qx),this.ym=new PG(a),this.P(this.ym),xG(this.Qx,{eh:this.ym}));this.si=new HG(a);this.P(this.si);this.ku((0,z.s)(function(a){this.H=a;this.P(this.H);a=this.H;this.ca&&a&&a.O(this.Lh,!0)},this))}};
XG.prototype.r=function(){return{EN:z.v.N.HC,FN:(0,window.encodeURIComponent)(String(window.location.href)),qb:this.g.pa.qb,Xh:this.L.Xh(),Rd:this.L.Rd(),Ly:!this.g.pa.Yx&&!z.v.VI,GX:this.g.pa.Yx,hq:this.L.hq()}};z.au={oO:"fyre-archive-stream",pO:"fyre-archive-stream-header",oR:"fyre-top-content-stream",k3:"fyre-widget",so:"fyre-featured-content-wrapper"};(0,z.cb)(z.au,z.mB);z.m=XG.prototype;
z.m.o=function(){var a=z.au;this.c=(0,z.Gl)(CG,this.r());var b=z.au,c=this.L.get(z.U.mm);if(c!==cH.NONE){var d=this.g.Qb,c=c===cH.lm?3:4,b=this.n(b.oR);(0,z.ru)(d,c,b,this)}this.It.O(this.n(a.xP));this.ym&&(d=this.n(a.pO),this.Qx.O(d),this.ym.O(this.n(a.oO)),a=this.n(a.uF),(0,z.L)(a,!1));this.pb(1)};
z.m.m=function(){XG.b.m.call(this);var a=this.H;this.ca&&a&&a.O(this.Lh,!0);this.g.J.uv("stream_data_received",this.oV,this);this.p().f(this,"request_content_context",this.NU).f(this,"request_content_reply",this.wW);this.ym&&this.ym.start()};z.m.lj=function(){this.Ap&&this.Ap.lj();this.Af.lj()};z.m.oV=function(){var a=this.L,b=a.get(z.U.$l);z.Yc||b||(b=(0,z.s)(function(){this.ru=new z.eH(this.g,a.get(z.U.xe));this.P(this.ru,!0)},this),(0,z.rb)(z.v.N.sb+z.v.Oe.ru,null,null,b))};
z.m.hK=function(a){var b=new z.Rw(this.rL,this);b.iM=(0,z.s)(this.WZ,this,a);a=(0,z.s)(function(){b.start(0,2E3)},this);(0,z.rb)(z.v.N.sb+z.v.Oe.AT,null,null,a)};z.m.WZ=function(a){var b=a.size;a=a.isComplete;var c=this.n(z.au.so);this.Xy=new z.VD(b,a,this.g);this.P(this.Xy);this.Xy.O(c);this.Xy.cg()};z.m.ku=function(a){if(!this.g.pa.readOnly){var b=z.Fu.F(),c=(0,z.s)(function(b){b=new b(this.g,{jg:this.g.pa.jg,wh:this.g.pa.wh,jI:this.L,$i:this.g.pa.$i});a(b)},this);(0,z.Gu)(b,"main",c)}};
z.m.kj=function(){0<(0,z.dm)(this,this.H)&&(this.removeChild(this.H),this.H.q());this.ku((0,z.s)(function(a){this.H=a;this.P(this.H);a=this.H;this.ca&&a&&a.O(this.Lh,!0)},this))};z.m.Th=function(a){null!=a&&(this.g.Qb.Ym(1),(0,window.setTimeout)((0,z.s)(function(){this.Wa||YG(this,a)},this),3E3))};z.m.NU=function(a){YG(this,a.Fs)};z.m.wW=function(a){YG(this,a.Fs,function(a){(0,z.Ws)(a.Sc)})};z.m.j=function(){XG.b.j.call(this);this.L&&(this.L.off(null,null,this),this.L=null)};(0,z.u)(ZG,z.Au);z.m=ZG.prototype;z.m.tf=function(a,b){ZG.b.tf.call(this,a,b);a.f(b,"repliesExpanded",this.hV);a.f(b,"sortHotThreads",this.JW);a.f(b,"sortOrderChanged",this.JK);a.f(b,"sortTopComments",this.KW);a.f(b,"archiveShowMore",this.uU);a.f(b,"archiveSortOrderChanged",this.vU)};
z.m.uU=function(a){var b=a.Rb||z.p;a=(0,z.s)(this.sf,this,a.target);var c=this.g.tb;c.xm||(c.xm=new uG(c.t));var c=c.xm,d=tG(c),f=c.Hf[d];f&&(c.kp=d);if(f)b(),a(f);else{c=this.g.tb.Um();d=c.d.zg;if(c.get(d))b();else c.on(c.Va(d),b,this);(0,z.Bu)(this,c,a)}};
z.m.Jz=function(a,b){var c=2===b.Fd,d=1!==b.Fd;switch(b.type){case z.Jr.ik:var f=this.g.v.B(),f=(0,z.Jj)(b,f),g=f.get(z.N.jb),g=this.g.v.nb().get(g);f.set(z.N.Ea,g);a.Wz(f,c,d);break;case z.Jr.Lw:a.Wk(EG(b),c,d);break;case z.Jr.Rr:a.Vp((0,z.Fj)(b),c,d)}};z.m.Bt=function(a){if(1!==this.Oo){var b=this.Q_.si;MG(b,!1);KG(b,b.Xn);(0,z.cb)(a,{direction:z.Fr.vd,Rb:z.p});this.JK(a)}};
z.m.vU=function(a){(0,z.Cu)(this);a.eh.Zo(a.direction);var b=this.g.tb.Um(a.direction,!0),c=(0,z.s)(function(b){a.Rb();this.sf(a.eh,b)},this);(0,z.Bu)(this,b,c,a.Ok)};z.m.JK=function(a){var b=(0,z.Eu)(this,1);(0,z.Vr)(this.g.tb);b.Zo(a.direction);var c=this.g.tb.gj(a.direction==z.Fr.vd?this.g.tb.Qb.Db:0),d=(0,z.s)(function(c){a.Rb();this.sf(b,c)},this);(0,z.Bu)(this,c,d,a.Ok)};
z.m.KW=function(a){var b=(0,z.Eu)(this,3),c=this.g.tb.ej("likes");(0,z.Bu)(this,c,(0,z.s)(function(c){a.Rb();(0,z.ab)(c)?(0,z.Lt)(b):this.sf(b,c)},this))};z.m.JW=function(a){var b=(0,z.Eu)(this,4),c=this.g.tb.hj();(0,z.Bu)(this,c,(0,z.s)(function(c){a.Rb();(0,z.ab)(c)?(0,z.Lt)(b):this.sf(b,c)},this))};
z.m.hV=function(a){var b=a.s,c=z.N,d=c.ew,f=c.XE,g=c.Ci;if(!b.get(f)){b.set(d,!0);var h=function(){b.set(g,a.ao.re)},c=(0,z.s)(function(c){b.set(g,a.ao.re,!1);b.set(f,!0);b.set(d,!1);(0,z.A)(c,(0,z.qa)(this.Jz,a.KS),this);this.Ba.f(a.ao,"threadVisChanged",h)},this),k=wG(this.g.tb,b);k.on(k.D.Ql,c,this);c(k.get(k.d.Cb))}};(0,z.u)($G,z.Lo);z.m=$G.prototype;z.m.c=null;z.m.j=function(){$G.b.j.call(this);this.tv.q();this.Nc.q();this.vg&&this.vg.q();delete this.vg};z.m.mn=function(a){$G.b.mn.call(this,a);this.tv=new ZG(this.g);this.tv.handle(a)};z.m.vC=function(){this.g.Bl.stop()};z.m.V_=function(){this.g.rq.stop()};z.m.xl=function(){this.g.Bl.start()};z.m.S_=function(){this.g.rq.start()};z.m.Ca=function(){this.vg&&this.vg.q();this.Nc.Ca(this.c);var a=(0,z.No)();this.Nc.Th(a);this.g.J.M("render_complete")};(0,z.u)(aH,z.fj);aH.prototype.rH=FG.F();aH.prototype.j=function(){aH.b.j.call(this);this.stop();delete this.pa;delete this.oa;bH(this);(0,z.kj)(this);this.Nk&&(this.Nk.q(),delete this.Nk)};aH.prototype.CC=function(){this.stop();bH(this);aH.b.CC.call(this)};z.Xb.main.Vi.la(aH);})(fyre.conv);

/*
//@ sourceMappingURL=sourcemap_livefyre_mod_main
*/
