var $body=$('body');var $shipping_options=$('#shipping_selection');var use_billing_info='input[name=use_billing_info]:checked';var $shipping_fields=$('input[type=text], input:not([type]), select','fieldset.shipping');$(document).ready(function(){$('.modal').fancybox();$(".modal-vimeo").fancybox({helpers:{media:true}});$(".scrollbar").mCustomScrollbar({set_width:false,set_height:false,horizontalScroll:false,scrollInertia:550,autoDraggerLength:false});$('.marquee').flexslider({animation:"slide",controlNav:false,directionNav:true});$('.recent-news-slider').flexslider({namespace:"ns-",animation:"slide",slideshow:true,controlNav:false,directionNav:false,touch:false});$('.marquee-featured, .marquee-stories').flexslider({animation:"slide",slideshow:false,controlNav:false,directionNav:true,prevText:"Previous",nextText:"Continue Reading",touch:false});$('.search-trigger').click(function(){$('.search-trigger').hide();$('.search-form-wrap').show("blind",{direction:"left"},500);$('#keywords').focus();return false;});$(".accordion").accordion({heightStyle:"content"});$('.zoom-gallery').jqzoom({zoomType:'standard',lens:true,preloadImages:true,alwaysOn:false,zoomWidth:460,zoomHeight:460,position:'right',title:false,zoomType:'reverse'});function aboutTab(){var activeContainer=$(window.location.hash);if(activeContainer.hasClass('full-width')){$pageTabs.find('.aside').hide().end().find('#about h2').hide().end().find('.grid_7').removeClass('grid_7');}else{$pageTabs.find('.aside').show().end().find('#about h2').show().end().find('.aside + div').addClass('grid_7');}}
var $pageTabs=$('.page-tabs').tabs({select:function(event,ui){window.location.hash=ui.tab.hash;aboutTab();}});aboutTab();$('body.customer-service').find('footer ul.customer-service a').click(function(){$pageTabs.tabs('select',this.hash);$(window).scrollTop(0);return false;});$('body.company').find('footer ul.company a').click(function(){$pageTabs.tabs('select',this.hash);$(window).scrollTop(0);return false;});$('body.legal').find('footer ul.legal a').click(function(){$pageTabs.tabs('select',this.hash);$(window).scrollTop(0);return false;});$('.product').find('.product-details form#add-product').validate();$('.shopping-bag').find('form.log-in').validate();$('.designers').find('form#mc-embedded-subscribe-form').validate();$('.account.register, .shopping-bag.log-in').find('form#register').validate({rules:{password:{required:true,minlength:5},password_confirm:{required:true,equalTo:'#register-password'}},messages:{password:{required:"",minlength:"Your password needs to be at least 5 characters long"},password_confirm:{required:"",equalTo:"Password does not match"}}});$('.account.register, .shopping-bag.log-in').find('form#register input#email').change(function(){$('input#member_email_address').val($(this).val());});if($body.hasClass('account')&&$body.hasClass('details')){var $accountForm=$('.account.details').find('form#account-details');$accountForm.find('button.password').click(function(e){e.preventDefault();$accountForm.get(0).setAttribute('action','{path="account/details/password-changed"}');$accountForm.find('input[name="return_url"], input[name="return"]').val("account/details/password-changed");$accountForm.find('input[name="RET"]').val("{path='account/details/password-changed'}");$accountForm.submit();});$accountForm.validate({rules:{password:{minlength:5},password_confirm:{required:function(element){return $("input#password").val()!='';},equalTo:"#password"},current_password:{required:function(element){return $("input#password").val()!='';}}},messages:{password:{minlength:"Your password needs to be at least 5 characters long"},password_confirm:{required:"Please confirm your new password",equalTo:"Password does not match"},current_password:{required:"Please enter your current password to change it"}}});}
if($body.hasClass('shopping-bag')&&$body.hasClass('payment')){if($('fieldset.shipping').hasClass('shipping_disabled')){disable_shipping_fields();}
$('.shopping-bag.payment').find('input.use_billing_info').change(function(){if($(this).val()==='1'){disable_shipping_fields();$('#state').change();}
else{enable_shipping_fields();$('#shipping_state').change();}});$('#shipping_country, #country').change(function(){var field_id=$(this).attr('id');var taget_dropdown=field_id=='country'?$('#state'):$('#shipping_state');var countryCode=$(this).val();$.get(baseURL+'shopping-bag/get-states/'+countryCode,function(options){if(options==''){taget_dropdown.empty().append('<option value="other">Other</option>');}else{taget_dropdown.empty().append(options);}
if($(use_billing_info).val()==='1'&&$(this).attr('id')=='shipping_country'){return;}
else if($(use_billing_info).val()==='0'&&$(this).attr('id')=='country'){return;}
var stateCode=taget_dropdown.val();show_available_shipping(stateCode,countryCode);});});$('#shipping_state, #state').change(function(){if($(use_billing_info).val()==='1'&&$(this).attr('id')=='shipping_state'){return;}
else if($(use_billing_info).val()==='0'&&$(this).attr('id')=='state'){return;}
var country_field=$(this).attr('id')=='state'?$('#country'):$('#shipping_country');show_available_shipping($(this).val(),country_field.val());});var ct_debug=false;function updating(){$('#checkout button[type=submit]').text('One moment...').attr('disabled','disabled');$('.payment-total .col2').html("updating...");}
function update_cart(data,statusText,xhr,$form){if(data.success){$form.find('input[name=XID]').val(data.XID);$('.payment-total').find('.subtotal .col2').html(data.cart_subtotal).end().find('.discount .col2').html('- '+data.cart_discount).end().find('.tax .col2').html(data.cart_tax).end().find('.shipping .col2').html(data.cart_shipping).end().find('.total .col2').html(data.cart_total);$('#checkout button[type=submit]').text('Submit & Pay').removeAttr('disabled');}
if(ct_debug)
{$.each(data,function(index,item){console.log(index+": "+item);});$.each(data.errors,function(index,item){console.log(index+": "+item);});}
return true;}
function show_available_shipping(state,country){$.get($shipping_options.data('endpoint')+'/'+state+'/'+country,function(data){$shipping_options.html(data);setTimeout(function(){$('form#shipping').submit();},1000);});}
var cart_form_options={beforeSerialize:updating,success:update_cart,dataType:'json'}
var bs_field_container='.shopping-bag.payment form#billing-info, .shopping-bag.payment form#shipping-info';$(bs_field_container).find('input, select').on('change keyup',function(){var obj=this;delay(function(){var $form=$(obj).parents('form');if($(obj).hasClass('email')){var email=$(obj).val(),emailReg=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;if(emailReg.test(email)){$(obj).removeClass('error');}}else{if($(obj).val()!=''&&$(obj).val()!='---'){$(obj).removeClass('error');}}
$form.ajaxForm(cart_form_options);$form.submit();if($form.attr('id')=='billing-info')
{$('form#checkout input[name="first_name"]').val($form.find('input[name="first_name"]').val());$('form#checkout input[name="last_name"]').val($form.find('input[name="last_name"]').val());}},1000);});$('.shopping-bag.payment').find('form#shipping').ajaxForm(cart_form_options);$('.shopping-bag.payment').find('form#shipping').submit();$('.shopping-bag.payment').on('change','form#shipping input',function(){var form=$('form#shipping');$(form).ajaxForm(cart_form_options);$(form).submit();});$('.shopping-bag.payment').find('form#checkout .card input, form#checkout .card select').on('change',function(){if($(this).val()!=''){$(this).removeClass('error');}});$('.shopping-bag.payment').find('form#checkout .btn').click(function(){var valid=true;$('.shopping-bag.payment form').find('.required').each(function(){if($(this).val()===''||$(this).val()=='---'){if($(this).parents('fieldset.shipping').length===1&&$(use_billing_info).val()==='1'){}
else{$(this).addClass('error');valid=false;}}});$('.shopping-bag.payment form').find('.min_length').each(function(){if($(this).val().length<2&&$(this).val().length>0&&($(this).parents('fieldset.billing').length===1||$(use_billing_info).val()==='0'))
{$(this).addClass('error');$('#name_length_error').fadeIn();setTimeout(function(){$('#name_length_error').fadeOut();},4000);valid=false;}});var shipping_option=$('input[name=shipping_option]:checked','#shipping').val();if(typeof shipping_option=='undefined'){$('#shipping_method_error').fadeIn();setTimeout(function(){$('#shipping_method_error').fadeOut();},4000);valid=false;}
if(valid==false){if($('.billing .error').length||$('.shipping .error').length){$('html, body').animate({scrollTop:$(".grid_12 h1").offset().top},100);}
return false;}
if(valid==true){return true;}});}});if($body.hasClass('customer-service')||$body.hasClass('company')||$body.hasClass('legal')){$(window).load(function(){$(this).scrollTop(0);})}
$(function(){var $product_details=$('#product-details');var $product_video_container=$('#product-video');var $product_video=$('iframe',$product_video_container);if($product_video_container.length>0)
{var player=$f($product_video[0]);var vid_transition=500;var hide_video=function(){if(!Modernizr.touch){$product_video.css('opacity',0);}};var show_video=function(){if(!Modernizr.touch){$product_video.fadeTo(vid_transition,1);}};hide_video();$('#product-video-trigger').click(function(event){$product_details.fadeOut(vid_transition,function(){$product_video_container.fadeIn(vid_transition,function(){if(!Modernizr.touch){player.api('play');}});});event.preventDefault();});player.addEvent('ready',function(){player.addEvent('finish',function(){$product_video_container.addClass('nobg');hide_video();video_reset();});player.addEvent('playProgress',function(data){if($product_video.css('opacity')<1&&data.seconds>0.40){show_video();}});});$('#product-video a.close').click(function(event){video_reset();event.preventDefault();});var video_reset=function(){$product_video_container.fadeOut(vid_transition,function(){$(this).removeClass('nobg');$product_details.fadeIn(vid_transition);if(!Modernizr.touch){player.api('seekTo',0);player.api('pause');}});};}});$(window).load(function(){var flexslider=$('.marquee-the-issue');flexslider.flexslider({animation:"slide",slideshow:false,controlNav:false,directionNav:true,prevText:"Previous",nextText:"Continue Reading",touch:false,startAt:0,randomize:false,start:function(slider){flexslider.removeClass('loading');}});});enable_shipping_fields=function(){$shipping_fields.removeAttr('disabled');};disable_shipping_fields=function(){$shipping_fields.attr('disabled','disabled').removeClass('error');};var delay=(function(){var timer=0;return function(callback,ms){clearTimeout(timer);timer=setTimeout(callback,ms);};})();