var pmc={is_empty:function(var_value){if(!var_value||var_value===null||var_value===undefined){return true;}
var_value=var_value+"";var_value=var_value.replace(/^\s+|\s+$/g,"");if(var_value===""){return true;}
return false;},has_json:function(){if(typeof JSON=='undefined'||!JSON){return false;}
return true;},_round:function(num,dec){dec=(this.is_empty(dec))?2:dec;return Math.round(num*Math.pow(10,dec))/Math.pow(10,dec);},_replace_all:function(needle,replace_with,haystack){var pattern=new RegExp(needle,'g');return haystack.replace(pattern,replace_with);},timestamp:function(){return Math.round(+new Date()/1000);},deeptest:function(obj_str){obj_str=obj_str.split('.');var obj=window[obj_str.shift()];while(obj&&obj_str.length){obj=obj[obj_str.shift()];}
return obj;},decode_entities:function(text){var element=document.createElement('div');if(text&&typeof text==='string'){text=text.replace(/<script[^>]*>([\S\s]*?)<\/script>/gmi,'').replace(/<\/?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gmi,'');element.innerHTML=text;text=element.textContent;element.textContent='';}
return text;},sanitize_title:function(text){if(!text||this.is_empty(text)||typeof text!=='string'){return'';}
var original_text=text;text=this.decode_entities(text);text=text.replace(/[^a-zA-Z0-9 \-_]/g,'');text=text.replace(/\s\-/g,'-').replace(/\-\s/g,'-').replace(/\s/g,'-');text=text.replace(/\-_/g,'-').replace(/_\-/g,'-');text=text.replace(/\-{2,}/g,'-');text=text.replace(/^\-/g,'').replace(/\-$/g,'');return text.toLowerCase();},cookie:{get:function(cookie_name){var x,y,i;var arr_cookie=document.cookie.split(";");var arr_cookie_len=arr_cookie.length;for(i=0;i<arr_cookie_len;i++){x=arr_cookie[i].substr(0,arr_cookie[i].indexOf("="));y=arr_cookie[i].substr(arr_cookie[i].indexOf("=")+1);x=x.replace(/^\s+|\s+$/g,"");if(x==cookie_name){return unescape(y);}}
return arguments.length>=2?arguments[1]:null;},set:function(cookie_name,cookie_value,expiry_secs,cookie_path){expiry_secs=parseInt(expiry_secs,10)*1000;var l_date=new Date();var expiry_date=new Date(l_date.getTime()+expiry_secs);cookie_value=escape(cookie_value);cookie_value+=(pmc.is_empty(expiry_secs))?"":"; expires="+expiry_date.toUTCString();cookie_value+=(pmc.is_empty(cookie_path))?"; path=/":"; path="+cookie_path;document.cookie=cookie_name+"="+cookie_value;},expire:function(cookie_name,cookie_path){cookie_path=(pmc.is_empty(cookie_path))?'':cookie_path;this.set(cookie_name,"",1,cookie_path);}},load_script:function(src,callback){if(typeof src==='undefined'){return;}
var loaded=false;var new_script=document.createElement('script');new_script.type='text/javascript';new_script.async=true;new_script.src=src;if(typeof callback==='function'){new_script.onreadystatechange=new_script.onload=function(){if(!loaded){loaded=true;callback();}
loaded=true;};}
var script=document.getElementsByTagName('script')[0];script.parentNode.insertBefore(new_script,script);},mobile_width:function(ignore_orientation){var width=0;try{if(typeof ignore_orientation==='undefined'){ignore_orientation=false;}
if(ignore_orientation||typeof window.orientation==='undefined'||window.orientation==0||window.orientation==180){width=window.screen.width;}
else{width=window.screen.height;}
if(typeof window.devicePixelRatio!='undefined'&&window.devicePixelRatio>1.0){width=width/window.devicePixelRatio;}}catch(e){}
return width;},tracking:{callback_on_removed:function(tracking_object){},_tokens:[],_extract_tokens:function(){if(typeof this._extraced!=='undefined'){return;}
this._extraced=true;this.remove(window.location.hash,true);this.remove(window.location.search,true);},get_properties:function(){this._extract_tokens();var arr=new Array();for(var name in this._tokens){arr.push({name:name,value:this._tokens[name]});}
return arr;},get_properties_string:function(){this._extract_tokens();var arr=new Array();for(var name in this._tokens){arr.push(name+'='+this._tokens[name]);}
return arr.join('&');},get_property:function(name,default_value){this._extract_tokens();return(typeof name==='undefined'||typeof this._tokens[name]==='undefined')?default_value:this._tokens[name];},remove:function(bufs,extract_tokens){var tracking=this;return bufs.replace(/(\?|#)([^#]*)/g,function(_,delim,search){search=search.split('&').map(function(v){if(extract_tokens&&/^utm_/.test(v)&&v&&/=/.test(v)){var pair=v.split('=',2);tracking._tokens[pair[0]]=pair[1];}
return!/^utm_/.test(v)&&v;}).filter(Boolean).join('&');return search?delim+search:'';});},remove_from_browser_url:function(){if(typeof this._removed!=='undefined'){return;}
this._removed=true;var scrollV,scrollH,loc=window.location;if("replaceState"in history){history.replaceState({},document.title,loc.pathname+this.remove(loc.search,true)+this.remove(loc.hash,true));}else{scrollV=document.body.scrollTop;scrollH=document.body.scrollLeft;loc.hash=this.remove(loc.hash,true);document.body.scrollTop=scrollV;document.body.scrollLeft=scrollH;}
if(typeof this.callback_on_removed==='function '){this.callback_on_removed(this);}},do_call_events:function(){this.remove_from_browser_url();}},geolocation:{cookie_name:'pmc_geo_data',expiry_secs:0,cookie_path:'/',get:function(){if(!pmc.has_json()||typeof geoPosition==='undefined'||!geoPosition){return false;}
var coords=pmc.cookie.get(this.cookie_name);if(coords==='false'){return false;}else if(!coords&&geoPosition.init()){geoPosition.getCurrentPosition(this._set,this._handle_errors);return false;}
return JSON.parse(coords);},_set:function(position){if(!pmc.has_json()||typeof position==='undefined'||typeof position.coords==='undefined'){return false;}
pmc.cookie.set(pmc.geolocation.cookie_name,JSON.stringify(position.coords),pmc.geolocation.expiry_secs,pmc.geolocation.cookie_path);},_handle_errors:function(error){if(typeof error==='undefined'){pmc.cookie.set(pmc.geolocation.cookie_name,'false',pmc.geolocation.expiry_secs,pmc.geolocation.cookie_path);}
var try_again=false;switch(error.code){case 1:case 2:try_again=false;break;case 3:default:try_again=true;break;}
if(!try_again){pmc.cookie.set(pmc.geolocation.cookie_name,'false',pmc.geolocation.expiry_secs,pmc.geolocation.cookie_path);}}}};