(function(){var g=!0,h=!1,i;
function k(a){function b(){f||(f=g,d?c.d.$=g:c.M())}var c=this,d=h,f=h;c.na=a.useFlashFallback===h?h:!c.ka;c.q=a.statBaseURL;c.w=a.guid;c.t=a.confID;c.b=a.viewableImpressionThreshold;c.xa=0;c.S=a.viewableImpressionTime;c.wa=h;c.n=a.customDefinition;c.j=0;c.T=h;c.width=parseInt(a.width,10);c.height=parseInt(a.height,10);c.target=c.e?null:window.parent.document.getElementById(a.divID)||window.frameElement;c.i=c.z=c.visibility.k;c.u=0;c.N=(new Date).getTime();c.O=(new Date).getTime();c.a={visible:0,
p:0,hidden:0,R:0};c.m=g;c.dispatchEvent=function(b,c){a.dispatchEvent(b,c)};if(a.fver&&a.minflashversion)this.G=!!a.fver();else{var e;e=h;if(this.s)for(var j=10;3<=j;j--)e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+j),e=!!parseFloat(e.GetVariable("$version").match(/\b\d+\b/g).join("."));else"undefined"!=typeof navigator.plugins["Shockwave Flash"]&&(e=!!parseFloat(navigator.plugins["Shockwave Flash"].description.substring(15)));this.G=e}c.e&&(window.A&&window.A.ca?c.o=c.la:"undefined"!==typeof window.mozInnerScreenY?
(c.J=c.da,c.L=c.ea):c.G&&!c.D&&c.na?(c.v={},d=g,c.d={$:h},c.g=[],window.ftPagefoldFlashListener=function(a){a=a.split("-");c.ga(a[0],parseInt(a[1],10))},c.o=c.ha,c.ba()):(c.c(this.event.Z),c.dispatchEvent("advisibility",h)));a.addEventListener("adonpage",b);a.addEventListener("backup",b)}
function l(a){var b="";this.q=a.statBaseURL;this.w=a.guid;this.t=a.confID;this.D=/fox/i.test(navigator.appVersion);b=this.e?window.document.referrer:window.parent.document.location;b=escape(String(b).substr(0,200));this.c("314",b)}
function m(){this.t=this.w=this.q="";this.ja=window!=top;this.e=h;if(this.ja)try{window.parent.document.getElementsByTagName("head")[0].appendChild(window.parent.document.createElement("script"))}catch(a){this.e=g}this.D=/fox/.test(navigator.userAgent);this.s=/MSIE/.test(navigator.userAgent);this.ka=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent)}k.prototype=new m;i=k.prototype;i.event={Y:"301",X:"302",C:"303",W:"304",U:"305",V:"306",B:"307",Z:"308",ra:"310",qa:"311",pa:"312"};
i.visibility={f:2,l:1,k:0};i.F=[50,175,300,600,1200,3E3];
i.M=function(){function a(){b.m=!document[f]}var b=this,c=this.o(),d=this.event.W,f,e;"undefined"!==typeof document.hidden?(f="hidden",e="visibilitychange"):"undefined"!==typeof document.ta?(f="mozHidden",e="mozvisibilitychange"):"undefined"!==typeof document.ua?(f="msHidden",e="msvisibilitychange"):"undefined"!==typeof document.ya&&(f="webkitHidden",e="webkitvisibilitychange");"undefined"!==typeof f?document.addEventListener(e,a,h):(e=b.e?window:window.parent,b.P(e,"focus",function(){b.m=g}),b.P(e,
"blur",function(){b.m=h}));1===c&&!b.n?d=this.event.Y:0<c&&(d=this.event.X);this.c(d);this.i=this.z=this.K(c);this.Q()};
i.Q=function(){var a=this,b=(new Date).getTime(),c=b-this.N,d=b-this.O,f=this.o(),e=this.K(f);a.m&&(this.dispatchEvent("advisibility",100*f),1==f?this.a.visible+=d:0<f?this.a.p+=d:this.a.hidden+=d,this.n&&(e===this.visibility.f?this.j+=d:this.j<this.S&&(this.j=0),!this.T&&this.j>=this.S&&(this.z===this.visibility.l?this.c(this.event.C):this.c(this.event.B),this.T=g)),e>this.i&&this.ma(e),this.u<this.F.length&&this.h(c)>=this.F[this.u]&&(this.fa(),this.N=b,this.u++),this.O=b);setTimeout(function(){a.Q()},
249)};i.fa=function(){var a=[this.h(this.a.visible)];a.push(this.h(this.a.p));a.push(this.h(this.a.hidden));a.push(this.h(this.a.R));this.c("310",a.join("x"));this.a.visible=0;this.a.p=0;this.a.hidden=0;this.a.R=0};i.ma=function(a){var b;this.i===this.visibility.k?a===this.visibility.l?b=this.event.U:a===this.visibility.f&&(b=this.event.V):this.i===this.visibility.l&&(a===this.visibility.f&&!this.n)&&(b=this.event.C,this.z===this.visibility.k&&(b=this.event.B));this.i=a;"undefined"!==typeof b&&this.c(b)};
i.o=function(){var a=this.J(),b=this.L();return this.aa(a,b)};i.la=function(){return window.A.ca.sa()/100};i.J=function(){return{x:this.I("Left",this.target),y:this.I("Top",this.target)}};i.I=function(a,b){var c="offset"+a,d=b,f=null!==d?d[c]:0;for("Top"!==a&&"Left"!==a&&this.error("1st argument must be 'Top' or 'Left'");null!==d&&null!==d.offsetParent;)d=d.offsetParent,f+=d[c];return f};
i.L=function(){var a={scrollLeft:0,scrollTop:0,height:0,width:0},b=window.parent;this.e||(b.innerWidth?(a.width=b.innerWidth,a.height=b.innerHeight,a.scrollLeft=b.pageXOffset,a.scrollTop=b.pageYOffset):b.document.documentElement&&b.document.documentElement.clientHeight?(a.width=b.document.documentElement.clientWidth,a.height=b.document.documentElement.clientHeight,a.scrollLeft=b.document.documentElement.scrollLeft,a.scrollTop=b.document.documentElement.scrollTop):b.document.body&&(a.width=b.document.body.clientWidth,
a.height=b.document.body.clientHeight,a.scrollLeft=b.document.body.scrollLeft,a.scrollTop=b.document.body.scrollTop));return a};i.aa=function(a,b){var c=0,d=0,c=Math.max(a.y,b.scrollTop),f=Math.min(a.y+this.height,b.scrollTop+b.height),d=Math.max(a.x,b.scrollLeft),e=Math.min(a.x+this.width,b.scrollLeft+b.width),c=this.H(f-c,this.height),d=this.H(e-d,this.width);return c*d};
i.K=function(a){var b=this.visibility.k;this.n&&a>=this.b?b=this.visibility.f:1===a?b=this.visibility.f:0<a&&(b=this.visibility.l);return b};i.da=function(){return{x:window.mozInnerScreenX,y:window.mozInnerScreenY}};i.ea=function(){return{scrollLeft:window.screenX,scrollTop:window.screenY,height:window.outerHeight,width:window.outerWidth}};i.ha=function(){var a=0,b=0,c;for(c in this.v)a+=300>this.v[c]?1:0;return b=0.5===this.b?1>a?0:5>a?0.1:9>a?this.b:1:1>a?0:8>a?0.1:12>a?this.b:1};
i.ga=function(a,b){var c=0;this.v[a]=b;this.d[a]=g;for(var d in this.d)this.d[d]||c++;0===c&&(this.M(),this.d.va=h)};
i.ba=function(){function a(a){return""+Math.round(a)}var b=Math.sqrt(this.b),c=[a(this.width*(1-b)),a(this.width*(1-this.b)),a(this.width*this.b),a(this.width*b)],b=[a(this.height*(1-b)),a(this.height*(1-this.b)),a(this.height*this.b),a(this.height*b)];this.g=[{id:"0",left:"0",top:b[0]},{id:"1",left:"0",top:b[3]},{id:"2",left:c[0],top:"0"},{id:"3",left:c[0],top:""+(this.height-1)},{id:"4",left:c[1],top:b[1]},{id:"5",left:c[1],top:b[2]},{id:"6",left:c[2],top:b[1]},{id:"7",left:c[2],top:b[2]},{id:"8",
left:c[3],top:"0"},{id:"9",left:c[3],top:""+(this.height-1)},{id:"10",left:""+(this.width-1),top:b[0]},{id:"11",left:""+(this.width-1),top:b[3]}];0.5===this.b&&(this.g=[{id:"0",left:"0",top:b[0]},{id:"1",left:"0",top:b[3]},{id:"2",left:c[0],top:"0"},{id:"3",left:c[0],top:+(this.height-1)},{id:"4",left:""+this.width/2,top:""+this.height/2},{id:"5",left:c[3],top:"0"},{id:"6",left:c[3],top:""+(this.height-1)},{id:"7",left:""+(this.width-1),top:b[0]},{id:"8",left:""+(this.width-1),top:b[3]}]);c=0;for(b=
this.g.length;c<b;c++){this.d[this.g[c].id]=h;var d=this.g[c],f=void 0,e="position: absolute; top: "+d.top+"px;",j=this.ia(d.id),e=e+(" width: "+this.r.width+"px;"),e=e+(" height: "+this.r.height+"px;"),e=e+(" left : "+d.left+"px; z-index: -1;");this.s?(f='<div style="@STYLE@">@FLASH@</div>'.replace("@STYLE@",e).replace("@FLASH@",j),document.body.insertAdjacentHTML("afterbegin",f)):(f=document.createElement("div"),f.style.cssText=e,f.innerHTML=j,document.body.appendChild(f))}};
i.ia=function(a){var b=this.r,c=b.name+a,d;d="<OBJECT "+(this.s?'classid = "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'data="'+b.path+'" type="application/x-shockwave-flash"');d=d+(' ID="'+c+'" name="'+c+'"')+(' width="'+b.width+'" height="'+b.height+'" style="float:left;">');d+='<PARAM NAME=movie VALUE="'+b.path+'"/>';d+='<PARAM NAME=FlashVars VALUE="identifier='+a+'"/>';d+='<PARAM NAME=quality VALUE="autohigh"/>';d+='<PARAM NAME=wmode VALUE="'+b.oa+'"/>';d+='<PARAM NAME="allowScriptAccess" value="always"/>';
d+='<PARAM NAME="allowFullScreen" value="true"/>';return d+="</OBJECT>"};i.r={path:("https:"===window.location.protocol?"https://secure":"http://cdn")+".flashtalking.com/pageFold/pagefold.swf",name:"ftPF",width:1,height:2,oa:"transparent"};i.H=function(a,b){return Math.max(Math.ceil(10*(a/b))/10,0)};i.h=function(a){return Math.ceil(a/100)};l.prototype=new m;
m.prototype.c=function(a,b){var c=[""+this.q+this.t];c.push(a);c.push("0");c.push(this.w);c.push(this.random());b&&c.push(b);this.q&&((new Image).src=c.join("-"))};m.prototype.random=function(a){return Math.floor(Math.random()*(a||1E9))};m.prototype.error=function(){};m.prototype.P=function(a,b,c){"function"===typeof a.addEventListener?a.addEventListener(b,c,h):a.attachEvent("on"+b,c)};window.ftPageFold_v3=function(a){new k(a);a.campaignID&&27400>parseInt(a.campaignID,10)&&new l(a)};}());
