window.pigeon=window.pigeon||{};
;(function(a){"undefined"===typeof a.dimensions&&(a.dimensions=function(a,b){this.width=a;this.height=b;this.toString=function(){return this.width+"x"+this.height}})})(pigeon);
;;(function(){pigeon.now=function(){return(new Date).getTime()}})();
;;;function ReadyHandler(){var b=!1,c=[];document.readyState in{complete:!0,interactive:!0}&&(b=!0);var a=function(){for(b=!0;0<c.length;)c.shift()()};document.addEventListener?(document.addEventListener("DOMContentLoaded",a,!1),window.addEventListener("load",a,!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",a,!1),window.attachEvent("onload",a));this.ready=function(a){b?a():c.push(a)}}
"undefined"==typeof pigeon.ready&&function(){var b=new ReadyHandler;pigeon.ready=function(c){b.ready(c)}}();
;
(function(h){function l(f){function m(a,b,e){var c=document.createElement("script");c.setAttribute("src",a);c.setAttribute("type","text/javascript");c.sayUsed=!0;var d=function(){"undefined"!=typeof e&&e.call(this,arguments);c.onreadystatechange=null;c.onload=null;b||c.parentNode.removeChild(c)};c.onload=d;c.onreadystatechange=function(){c.readyState in{loaded:1,complete:1}&&d.call(this,arguments)};return c}var n,g=[],l=0;"undefined"==typeof f&&(f=3E3);pigeon.ready(function(){n=document.getElementsByTagName("head")[0]});
var p=function(){g.shift()};this.attach=function(){for(var a=0;a<g.length;a++)document.body.appendChild(g[a])};this.fetch=function(a){var b;h.XMLHttpRequest?b=new XMLHttpRequest:h.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));b.open("GET",a,!1);b.send(null);pigeon.log.debug("pigeon.loader.fetch("+a+")");return b.responseText};this.fireRequest=function(a){var b=document.createElement("img");b.src=a;g.push(b);h.setTimeout(p,f)};this.loadScript=function(a,b){pigeon.ready(function(){n.appendChild(m(a,
0,b))})};this.jsonp=function(a,b,e,c,d){pigeon.log.debug("pigeon.loader.jsonp()");"undefined"===typeof d&&(d=3E3);var g=h.setTimeout(function(){c();delete pigeon.loader[k]},d),k="jsonp_"+l++;pigeon.loader[k]=function(){h.clearTimeout(g);c.apply(this,arguments);delete pigeon.loader[k]};e[b]="pigeon.loader."+k;b="?";d="";for(var f in e)d+=b+f+"="+escape(e[f]),b="&";pigeon.log.debug("JSONP: "+a+d);this.loadScript(a+d)};this.insertScript=function(a,b,e){a=m(a,1,e);b.parentNode.insertBefore(a,b);return a};
this.appendScript=function(a,b,e){a=m(a,1,e);b.appendChild(a);return a}}"undefined"==typeof pigeon.loader&&(pigeon.loader=new l())})(window);
;;;(function(){if("undefined"==typeof pigeon.topWindow){var a;pigeon.testWindow=function(a){try{var b=a.document.body,c=b.insertBefore(a.document.createComment("accessible"),b.firstChild);b.removeChild(c);return!0}catch(d){return!1}};pigeon.topWindow=function(){if("undefined"===typeof a){try{"undefined"!==typeof top.document&&(a=top)}catch(e){}"undefined"==typeof a&&(a=window);a=pigeon.findTopWindow(a);pigeon.testWindow(a)||(a=window)}return a};pigeon.findTopWindow=function(a){try{var b=a.document;if("FRAMESET"==
b.body.nodeName){for(var c=window;c.parent!==c.parent.parent;c=c.parent);for(var d=b.body.getElementsByTagName("frame"),b=0;b<d.length;b++)if(c===d[b].contentWindow)return c}}catch(f){}return a}}})();
;
(function(e,c,f){function g(c){this.isDebug=/(debug|extispicy)=1/.test(e.location.toString());var d=function(a,b){"undefined"!=typeof console&&console.log(a+" "+(new Date).toString()+" "+b);c&&f.fireRequest("//"+c+"/log/"+a.toLowerCase()+"?msg="+encodeURI(b))};this.error=function(a,b){"undefined"!==typeof b&&"undefined"!==typeof b.stack&&(a+=" caused by "+b.message+" at:\n"+b.stack);d("ERROR",a)};this.debug=function(a){this.isDebug&&d("DEBUG",a)}}"undefined"==typeof c.log&&(c.log=new g("ads.saymedia.com"))})(pigeon.topWindow(),
pigeon,pigeon.loader);
;window.deferred=function(b,e){var c=[],a=function(){c.push(arguments)};a.implement=function(a){for(var d=0;d<c.length;d++)a.apply(b,c[d]);b[e]=a};b[e]=a};
;
(function(){function k(a){var f=!1;"undefined"!==typeof a&&(f=!0,"/"!=a[a.length-1]&&(a+="/"),/\w*:\/\//.test(a)||(a="//"+a));this.send=function(g,b,d){if(f){pigeon.log.debug(g+": "+b);var c=new Date;"undefined"==typeof d&&(d={});if("string"!==typeof b||!/^[0-9a-fA-F]+$/.test(b))throw pigeon.log.error("beacon.send(name, rid) rid must be a hexadecimal string"),Error("beacon.send(name, rid) rid must be a hexadecimal string");d.rid=b;d.curtime=c.getTime();d.curtz=c.getTimezoneOffset();b=[];var e;a:for(e in d)switch(c=
d[e],typeof c){case "number":case "boolean":case "string":b.push(escape(e)+"="+escape(c));continue a;case "object":if(c.constructor==Array){for(var h=0;h<c.length;h++)b.push(escape(e)+"="+escape(c));continue a}break;default:pigeon.log.error("parameter "+e+" unknown type")}pigeon.loader.fireRequest(a+g+"?"+b.join("&"))}};this.exception=function(){};deferred(this,"demo")}"undefined"==typeof pigeon.beacon&&(pigeon.beacon=new k("beacon.saymedia.com"))})();
;;
(function(d){function f(){this.add=function(a,c,b){if(a.addEventListener)a.addEventListener(c,b);else if("function"===typeof jQuery)jQuery(a).on(c,b);else a.attachEvent&&a.attachEvent("on"+c,b)};this.remove=function(a,c,b){a.removeEventListener?a.removeEventListener(c,b):"function"===typeof jQuery?jQuery(a).off(c,b):a.detachEvent&&a.detachEvent("on"+c,b)};this.trigger=function(a,c,b){var e=a.ownerDocument;if(a.dispatchEvent&&e.createEvent){e=a.ownerDocument.createEvent("Event");e.initEvent(c,!0,!0);
if("undefined"!==typeof b)for(var d in b)e[d]=b[d];a.dispatchEvent(e)}else"function"===typeof jQuery&&jQuery(a).trigger(c,b)}}"undefined"===typeof d.event&&(d.event=new f)})(pigeon);
;;(function(){function a(a){var b=!1;this.loadCollector=function(){b||(pigeon.ready(function(){window.setTimeout(function(){pigeon.loader.loadScript("http://"+a+"/demo.js")},0)}),b=!0)}}"undefined"==typeof pigeon.demographics&&(pigeon.demographics=new a("ads.saymedia.com"))})();
;;
(function(){"undefined"==typeof pigeon.createIframe&&(pigeon.createIframe=function(b,c,a){"undefined"==typeof a&&(a=window.document);a=a.createElement("iframe");c&&(a.src=c);a.setAttribute("frameBorder","0");a.setAttribute("marginWidth","0");a.setAttribute("marginHeight","0");a.setAttribute("allowTransparency","true");a.setAttribute("scrolling","no");a.setAttribute("vspace","0");a.setAttribute("hspace","0");a.style.padding="0px";a.style.marginTop="0px";a.style.marginLeft="auto";a.style.marginRight=
"auto";/^\d+x\d+$/.test(b)&&(b=b.split("x"),a.style.width=Number(b[0])+"px",a.style.height=Number(b[1])+"px");return a})})();
;(function(){"undefined"===typeof pigeon.writeDocument&&(pigeon.writeDocument=function(a,c){var b=a.contentDocument||a.contentWindow&&a.contentWindow.document;b.open();window.setTimeout(function(){b.write("<!DOCTYPE html><html><head><style>body {margin: 0px;background: transparent;}</style></head><body>"+c+'<script type="text/javascript">document.write("</body></html>");setTimeout(function(){document.close()},1)\x3c/script>')},0)})})();
;
;if("undefined"==typeof JSON||'{"test":["1"]}'!=JSON.stringify({test:["1"]}))JSON={},JSON.stringify=JSON.stringify||function(a){var c=typeof a;if("object"!=c||null===a)return"string"==c&&(a='"'+a+'"'),String(a);var d,b,f=[],e=a&&a.constructor==Array;for(d in a)b=a[d],c=typeof b,"function"!=c&&("string"==c?b='"'+b+'"':"object"==c&&null!==b&&(b=JSON.stringify(b)),f.push((e?"":'"'+d+'":')+String(b)));return(e?"[":"{")+String(f)+(e?"]":"}")},JSON.parse=JSON.parse||function(a){return eval("("+a+")")};
;
;;function CookieService(b,e,f){var g="http://"+b+e,c={},d={},h=function(a){return function(){pigeon.loader.fireRequest(g+"?"+a+"="+c[a]);delete d[a];delete c[a]}};this.store=function(a,b){c[a]=b;d[a]||(d[a]=window.setTimeout(h(a),f))}}"undefined"==typeof pigeon.cookieService&&(pigeon.cookieService=new CookieService("ads.saymedia.com","/c",350));
(function(){function c(c,b){this.get=function(a){return b[a]};this.update=function(){pigeon.cookieService.store(c,JSON.stringify(b))};this.set=function(a,c){b[a]=c;this.update()};var d=function(a){return a.replace(/\D+/g,",").match(/^,?(.+),?$/)[1]},e=function(){if("undefined"!=typeof ActiveXObject)try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");return d(a.GetVariable("$version"))}catch(b){}try{return navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin?d((navigator.plugins["Shockwave Flash 2.0"]||
navigator.plugins["Shockwave Flash"]).description):"0,0,0"}catch(c){return"0,0,0"}};this.flashVersion=function(){var a=b.fv;"undefined"==typeof a&&(a=e(),b.fv=a,this.update());return a};this.isTrackable=function(){return"undefined"===typeof b.untrackable?!0:!1}}"undefined"==typeof pigeon.user&&(pigeon.user=new c("u0",{"impressionHistory":["5292322-1","5320718-1"],"userId":"52ba1bf1b4f07c5543d95adb0a0200cd","dims":"1440x808","fv":"11,9,900"}))})();
;(function(a,c){if("undefined"===typeof a.thirdPartyTracking){c=window.document;var f="http://ads-static.saymedia.com/static/jstags.html";a.thirdPartyTracking=function(d,e,g){a.user.isTrackable()&&a.ready(function(){var a="thirdparty_"+g;if(!c.getElementById(a)){var b=c.createElement("iframe");b.id=a;"undefined"===typeof e&&(e="0");b.src=f+"?CCID="+e+"&r="+Math.random();b.style.display="none";d.parentNode.insertBefore(b,d);setTimeout(function(){d.parentNode.removeChild(b)},5E3)}})}}})(pigeon,window);
(function(e,l,n){function h(){var f=function(a,b,c){var d=document.createElement("div");b=e.createIframe(b,c);d.appendChild(b);a.parentNode.insertBefore(d,a);return b},h={url:function(a,b,c){f(a,b,c)},js_tag:function(a,b,c){a=f(a,b);e.writeDocument(a,c)},js_function:function(a,b,c){eval(c)}};this.send=function(a,b,c,d,k,g){n.debug("passback.send [ action: "+a+" method: "+b+" value: "+c+" dimensions: "+d+" ]");if("no_backfill"!=a){var f=h[b];if("undefined"!=typeof f){try{f(k,
d,c)}catch(m){throw e.event.trigger("aderror",{rid:g,size:d,action:a,method:b,value:c,message:m.message}),m;}"partner_passback"==a?l.send("altloaded",g):"say_backfill"==a&&l.send("bannershown",g,{dim:d});if("300x600"==d){a=window.smBackfillLoaded;if(void 0===a)try{a=window.parent.smBackfillLoaded}catch(p){}"function"==typeof a&&a(k.parentNode)}}else throw Error("No handler for backfill method "+b);}e.demographics.loadCollector();e.thirdPartyTracking(k,"0",g);"function"==typeof iab_rma_noad&&iab_rma_noad()}}
"undefined"==typeof e.passback&&(e.passback=new h)})(pigeon,pigeon.beacon,pigeon.log);
;
(function(){function EventBus(){var g={},f={},e=function(b,a){return"string"!==typeof a?b:b+":"+a},d=function(b,a){a in b||(b[a]=[]);return b[a]};this.onListen=function(b,a,c){b=e(b,a);c="function"===typeof a?a:c;if("function"!=typeof c)throw Error("callback argument must be a function");d(g,b).push(c)};this.addListener=function(b,a,c){b=e(b,a);c="function"===typeof a?a:c;if("function"!=typeof c)throw Error("callback argument must be a function");a=d(f,b);a.push(c);for(a=d(g,b);0<a.length;)a.shift()();return!0};
this.removeListener=function(b,a,c){b=e(b,a);c="function"===typeof a?a:c;a=d(f,b);for(b=0;b<a.length;b++)if(c===a[b]){do b==a.length?a.pop():a[b]=a[b+1];while(b++<a.length);return!0}return!1};this.dispatch=function(b,a,c){b=e(b,a);"string"!==typeof a&&(c=a);"undefined"===typeof c&&(c={});a=d(f,b).slice(0);pigeon.log.isDebug&&pigeon.log.debug(b+" - "+JSON.stringify(c,function(a,b){return"impression"===a&&"object"===typeof b?"[object Impression]":b})+" ("+a.length+" listeners)");for(b=0;b<a.length;b++)if(!1===
a[b].call(this,c))return!1;return!0};this.dispatcher=function(b){var a=this;return{dispatch:function(c,d){a.dispatch(b,c,d)}}}};
;pigeon.impression=function(h,d,n,k,p,q,r,l,s,a,t){EventBus.call(this);var c=a;a=[];"string"==typeof c&&(c=[c]);for(var m="relative",e=0;e<c.length;e++){var f=c[e].match(/fixed_(top|bottom)/);f?(a.push(void 0),m=f[1]):1<=c[e].indexOf("x")&&(f=c[e].split("x"),a.push(new pigeon.dimensions(f[0],f[1])))}a.sort(function(g,a){if("undefined"==typeof g)return"undefined"==typeof a?0:-1;if("undefined"==typeof a)return 1;var b=a.width-g.width;return 0===b?a.height-g.height:
b});var b={method:d.backfillMethod,value:d.backfillValue};b.action="undefined"!==typeof d.backfillIsInternal?d.backfillIsInternal?"say_backfill":"partner_passback":"no_backfill";this.backfill=b;this.position=m;this.rid=h;this.product=n;this.integrationId=d.id;this.integration=d;this.time=k;this.top=q;this.document=r;this.node=l;this.topNode=s;this.dimensions=a;this.specification=p;this.elapsed=function(){return pigeon.now()-k};this.meta=t;this.insertCreative=function(a){if("undefined"==typeof a)throw a=
"insertCreative(node) requires node argument",pigeon.log.error(a),Error(a);if(a.ownerDocument!==this.document)throw a="The node given to insertCreative must belong to impression document.",pigeon.log.error(a),Error(a);var b=this.node;b.parentNode.insertBefore(a,b)};this.passback=function(){pigeon.log.debug("impression.passback()");this.dispatch("supervisor","passback",{size:a,action:b.action,method:b.method,value:b.value});pigeon.passback.send(b.action,b.method,b.value,a.join(","),l,h)}}})();
;
;;;
(function(n,A,B,g){function q(r,s){"undefined"===typeof s&&(s={});var v={dom:function(d,e,c,a){if("string"!==typeof a)throw Error("DOM target must be event name");return function(b){g.debug("demux.DOM: "+a);b.rid=d.rid;b.integrationId=d.integrationId;b.impression=d;A.trigger(d.node,a,b)}},beacon:function(d,e,c,a){if("string"!==typeof a)throw Error("event target must be a beacon name");return function(b){g.debug("demux.beacon: "+a);B.send(a,d.rid,b)}},event:function(d,e,c,a){if("string"!==typeof a)throw Error("event target must be an event name");
return function(b){g.debug("demux.event: "+a);d.dispatch(e,a,b)}},report:function(d,e,c,a){if(a.constructor!==Array)throw Error(e+":"+c+" event report specification must be an argument mapping, in the form of an array.");return function(b){var c=d.report,e=a[0];g.debug("demux.report: "+e);for(var l=[],h=1;h<a.length;h++)l.push(b[a[h]]);if("function"===typeof c[e])c[e].apply(c,l);else throw b="report object has no method "+e,n.log.error(b),Error(b);}},"function":function(d,e,c,a){return function(b){var c=
window[a];g.debug("demux.function: "+a);"function"===typeof c&&c.call(d,d.node.parentNode,b)}}},m=function(d){var e=[],c;for(c in d)d.hasOwnProperty(c)&&e.push(c);return e},t=function(d,e){var c=m(d).concat(m(e));if(1<c.length){c.sort();for(var a=0,b=0;b<c.length;a++)for(a!==b&&(c[a]=c[b]);c[a]===c[b];)b++;c.splice(a,b-a)}return c},q=function(d,e,c,a){var b=function(){d.removeListener(e,c,b);return a.apply(this,arguments)};return b};this.attach=function(d){for(var e=s[d.product]||{},c=t(r,e),a=0;a<
c.length;a++)for(var b=c[a],g=r[b]||{},m=e[b]||{},l=t(g,m),h=0;h<l.length;h++)for(var k=l[h],w=g[k]||{},x=m[k]||{},y=t(w,x),u=0;u<y.length;u++){var f=y[u],z=!1,p=x[f];"undefined"===typeof p&&(p=w[f]);null!==p&&("+"==f.substring(0,1)&&(z=!0,f=f.substring(1)),v.hasOwnProperty(f)||n.log.error("Unknown dispatch type "+b+":"+k+" "+f),f=v[f](d,b,k,p),z&&(f=q(d,b,k,f)),d.addListener(b,k,f))}};this.getRules=function(){return r.clone()}}"undefined"===typeof n.demux&&(n.demux=new q({"supervisor":{"vericount":{"+report":["vericount"]},"passback":{"dom":"adpassback","beacon":"altloaded"},"abandoned":{"beacon":"abandoned"},"exposed":{"+beacon":"exposed","+report":["exposed"]}},"loader":{"rollout":{"beacon":"rollout"},"visible":{"report":["visible","value"]},"rollover":{"beacon":"rollover"}},"creative":{"timeinvideo":{"report":["timeInVideo","vidid","tivprct"],"beacon":"timeinvideo"},"takeoverclosed":{"dom":"admediastop","function":"iab_rma_stop","beacon":"takeoverclosed"},"loaded":{"+dom":"addelivery","+beacon":"bannershown","+report":["shown"]},"videocompleted":{"report":["videoCompleted","vidid"],"dom":"admediastop","function":"iab_rma_stop","beacon":"videocompleted"},"takeovershown":{"dom":"admediastart","function":"iab_rma_start","beacon":"takeovershown"},"engaged":{"beacon":"optin"},"videoended":{"event":"videocompleted"},"ctaclicked":{"report":["click"],"beacon":"ctaclicked"},"videostarted":{"report":["videoStarted","vidid"],"dom":"admediastart","function":"iab_rma_start","beacon":"videostarted"},"engagement":{"+dom":"adengagement","+report":["engagement"],"beacon":"engagement"}}},{"fscr":{"supervisor":{"obscured-100":{"beacon":"obscured-100"},"exposed-25":{"beacon":"exposed-25"},"obscured-25":{"beacon":"obscured-25"},"exposed-100":{"beacon":"exposed-100"},"obscured-75":{"beacon":"obscured-75"},"exposed-50":{"beacon":"exposed-50"},"exposed-75":{"beacon":"exposed-75"},"obscured-50":{"beacon":"obscured-50"}},"loader":{"visiblechanged":{"report":["visibilityChange","state","direction","value"]}}},"af3":{"supervisor":{"vericount":{"+report":null}},"creative":{"screenshown":{"event":"engagement","beacon":"screenshown"},"ctaclicked":{"report":null},"videostarted":{"dom":null,"function":null,"beacon":"videostarted"},"videocompleted":{"dom":null,"function":null,"beacon":"videocompleted"}}},"sparkvid":{"supervisor":{"vericount":{"+report":null}},"creative":{"ctaclicked":{"report":null},"videostarted":{"event":"engagement"}}},"spotlight":{"supervisor":{"vericount":{"+report":null}},"creative":{"ctaclicked":{"report":null}}},"spark":{"supervisor":{"vericount":{"+report":null}},"creative":{"ctaclicked":{"report":null}}}}))})(pigeon,
pigeon.event,pigeon.beacon,pigeon.log);
(function(){;;(function(d){"function"!=typeof d.claimTag&&(d.claimTag=function(d,e){var c,a=document.getElementById(e),g=document.getElementsByTagName("script");if(!a||"SCRIPT"!==a.nodeName)for(var f=0;f<g.length;f++){var b=g[f];"string"===typeof b.src&&-1<b.src.indexOf(d)&&(b.sayUsed?b.rid===e&&(c=b):a=b)}!c&&a&&(a.sayUsed=!0,c=a,a.id||(a.id=e),c.rid=e);return c})})(pigeon);
;;var k="ai0162fc719589970d017ee6e98fe6970d",g="532c6d4dab1fcf8e984a5ada0a0200cc";"140x150";var h={"editedTime":"2013-01-09T18:13:22Z","status":"active","isTrafficable":true,"dimensions":"140x150","dfpId":"BD_FASHIONISTA-140X150-BTF-RIGHTRAIL-7_ai0162fc719589970d017ee6e98fe6970d","createdTime":"2013-01-03T19:42:00Z","acceptedProductFamilyKeywords":["content"],"backfill":"javascript:handleNoAd('7','1');","objectType":"AdIntegration","id":"ai0162fc719589970d017ee6e98fe6970d","adtechPlacementId":"2682439","products":["content","tile"],"displayName":"FASHIONISTA-140X150-BTF-RIGHTRAIL-7","defaultPlacementId":"","backfillType":"js_function","backfillMethod":"js_function","iframeBusterUrl":"","languageKeyword":"en","backfillValue":"handleNoAd('7','1');","backfillIsInternal":false,"partner":{"editedTime":"2012-12-03T22:06:48Z","status":"active","audienceOwnerUserId":"6p017744d9cc70970d","recruiterUserId":"6p0153919a3a55970b","migrationStatus":"finalized","salesforceId":"0017000000iZddjAAC","createdTime":"2011-01-26T23:36:45Z","billingAddress":{"street":"Breaking Media\r\n611 Broadway, Suite 907D\r\nNew York, New York 10012"},"objectType":"AdPartner","id":"ap0162fc719589970d","phoneNumber":"(212) 334-1871","payeeIsCorporation":false,"displayName":"Fashionista"},"alternateUrl":"javascript:handleNoAd('7','1');"},l={"integration_id":"ai0162fc719589970d017ee6e98fe6970d","dimensions":"140x150","engagementHistory":null,"21+":"118","hispanic":"177","parentkidsallages":"100","device_type":"pc","impressionHistory":"5292322-1,5320718-1","placement_id":"2682439","platform":"windows","request_id":"532c6d4dab1fcf8e984a5ada0a0200cc","18-34":"170","products":"content:tile","18+":"112","male":"183","categories":"","25+":"113","expandable":1,"25-54":"126","badword":"0","tile_group":"52426"},m="http://adserver.adtechus.com/adrawdata/3.0/5108.1/2682439/0/0/ADTECH;kvdim=140x150;kvagt21=118;kvehisp=177;kvpall=100;kvdc=pc;kvrti=5292322-1,5320718-1;kvpid=2682439;kvosplatform=windows;kvrid=532c6d4dab1fcf8e984a5ada0a0200cc;kva1834=170;kvprods=content:tile;kvagt18=112;kvgm=183;kvpcc=;kvagt25=113;kvexpandable=1;kva2554=126;kvbw=0;grp=52426;cfp=1;ip=38.125.10.16";pigeon.ready(function(){var c=pigeon.claimTag(k,g),a=pigeon.topWindow(),e=a.document,n=h.dimensions,f=c;if(e!==document&&document!==window.top.document){for(var b=window;b.parent!==a&&b.parent!==b.top;)b=b.parent;if(b.parent===a)for(var a=
e.getElementsByTagName("iframe"),d=0;d<a.length;d++)if(a[d].contentWindow===b){f=a[d];break}if(f===c)throw pigeon.log.error("Unable to find top document impression node."),Error("Unable to find top document impression node.");}c=new pigeon.impression(g,h,void 0,pigeon.now(),null,e,document,c,f,n,{targets:l,adtechUrl:m});pigeon.demux.attach(c);c.passback()})})();
