(function(z){
var CI=function(a,b,c){b="new"===(b||a.Vc);return c?(a=a.d.u.v().get(z.W.vo),b?-1:-a):a.nm+(b?-1:1)};var DI=function(a){z.ju.call(this,a);this.nm=0;this.Vc="new"};var EI=function(a,b){a.nT=b};var FI=function(a){return a.get(a.j.Co)};
var GI=function(a){return'\x3ca href\x3d"'+(0,z.Ml)(a.za)+'" title\x3d"'+(0,z.R)(a.W)+'" data-id\x3d"'+a.id+'" class\x3d"fyre-follower fyre-follower-'+a.TP+'"\x3e\x3cimg src\x3d"'+(0,z.Ml)(a.kd)+'" alt\x3d"'+(0,z.R)(a.W)+'" onerror\x3d"javascript:this.src\x3d\''+(0,z.R)(a.Qb)+"';\" /\x3e\x3c/a\x3e"};
var HI=function(a){return(0,z.Gt)(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3\x3e\x3cstrong\x3e\x3c/strong\x3e'+(0,z.R)(a.k.TK)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.R)(a.k.dw)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(a.k.Kn)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+(0,z.R)(a.k.ew)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e"};
var II=function(a){return'\x3cdiv class\x3d"fyre '+(a.Sd?"fyre-liveblog ":"")+(a.Fh?"fyre-livechat ":"")+(a.hQ?"fyre-bootstrap":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Na?"fyre-avatar-disabled":"")+'"\x3e'+(a.Xt?(0,z.nr)(a):"")+'\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Na?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.dn?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'};var JI=function(a){return'\x3cdiv class\x3d"tooltip"\x3e'+(0,z.R)(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e'};var KI=function(){};var LI=function(a,b){z.Kj.call(this,b,a)};var MI=function(a,b){z.ID.call(this,a,b)};
var NI=function(a,b){var c=a.d.xb;c.Sg[4]&&((0,z.dx)(c,4,(0,z.t)(function(a){b.f(a,"threadBreakout",this.oq)},a)),(0,z.fx)(c,4,(0,z.t)(function(a){b.Ya(a,"threadBreakout",this.oq)})))};var OI=function(a,b){var c=[a.vl,a.kx];a.bg&&c.push(a.bg);a.Qr&&c.push(a.Qr);a.lx&&c.push(a.lx);(0,z.x)(c,function(a){(0,z.ii)(a,"fyre-stream-sort-selected")});(0,z.F)(b,"fyre-stream-sort-selected")};var PI=function(a,b){z.ID.call(this,a,b)};
var QI=function(a,b){z.$v.call(this,a,b);this.Pk=!1;this.Ha=new z.hw;this.Ha.gc(this);this.Ns="archiveShowMore"};var RI=function(a,b){z.GD.call(this,a,b)};var SI=function(a,b,c){z.Cs.call(this,a,b,c);this.Cx=b||"";this.$f(JI(this.s()))};var TI=function(a,b,c){z.ws.call(this,a,b||3,c)};var UI=function(a,b){z.U.call(this,b);this.m=a};var VI=function(a,b){z.U.call(this,b);this.Tb=a};var WI=function(a,b){VI.call(this,a,b)};var XI=function(a,b,c,d,f){z.HD.call(this,a,b,c,d,f)};
var YI=function(a,b){z.QD.call(this,a,b);var c=a.u.Bb(),d=a.u.v();this.Uf=new XI(a,c,a.$k.hb,d.Fh()||z.cg);this.G(this.Uf);a.ca.Na||(this.Cm=new WI(c),this.G(this.Cm));this.uq=new z.FD;this.G(this.uq)};var ZI=function(a){var b=z.H.rc();return!a.F.Sd()||b};var $I=function(a){z.jx.call(this,a);this.Tl=1};var aJ=function(a){z.qr.call(this,a);(0,z.Et)(a.u);this.Lb=new YI(a);this.Hp.start();this.Ok(this.Lb);(0,z.ur)(this)};
var bJ=function(a,b){this.aB=LI;this.VG=aJ;z.Y.Pn(b.strings||{});z.tl.call(this,a,b)};var cJ=function(a){a.Fj&&(a.Fj.q(),delete a.Fj)};(0,z.v)(DI,z.ju);DI.prototype.Dk=(0,z.l)(3);DI.prototype.rD=(0,z.l)(62);DI.prototype.sD=(0,z.l)(25);DI.prototype.rD=(0,z.O)(62,function(a){this.Ra||(this.wn[a]=!1,(0,z.ku)(this,a,function(a){a.L(a.qa.Rl)}))});z.wt.prototype.uh=(0,z.O)(51,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/hot/",z.w.J.ld,z.w.Oe,a.la);(new z.Je({url:a,ta:b,na:c})).send()});
z.Cu.prototype.uh=(0,z.O)(50,function(a){var b={la:this.d.u.v().id},c=z.wt.B().uh;(0,z.Du)(this,c,b,a);return a});z.lE.prototype.uh=(0,z.O)(49,function(){(0,z.Iu)(this);this.bi=new z.Cu(this.H,void 0);var a=new z.fu;this.bi.uh(a);return a});z.U.prototype.xE=(0,z.O)(42,function(){return this.aa});z.Hj.prototype.dn=(0,z.O)(31,function(){return this.get(this.j.uo)});
DI.prototype.sD=(0,z.O)(25,function(a,b){if(!this.Ra){var c=this.d.u.v(),d=(0,z.dt)(a,b);c.set(z.W.vo,d.hR);(0,z.C)(d.Za,(0,z.t)(this.d.O.L,this.d.O,"bootstrap_author_received"));(0,z.C)(d.content,function(a){(0,z.D)(d.content,(0,z.lu)(this,a))},this);(0,z.D)(this.Bc,(0,z.nj)(d.content,(0,z.xb)(a)));this.Gd(a,d.content);(0,z.ku)(this,a,function(b){b.L(b.qa.Vj,{sd:a});b.set(b.j.Qe,!0)})}});
z.wt.prototype.rh=(0,z.O)(6,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/top/%s/",z.w.J.ld,z.w.Oe,a.la,a.MK);(new z.Je({url:a,ta:b,na:c})).send({format:"stream"})});z.Cu.prototype.rh=(0,z.O)(5,function(a,b){var c={la:this.d.u.v().id,MK:a},d=z.wt.B().rh;(0,z.Du)(this,d,c,b);return b});z.lE.prototype.rh=(0,z.O)(4,function(a){(0,z.Iu)(this);this.bi=new z.Cu(this.H,void 0);var b=new z.fu;this.bi.rh(a,b);return b});
DI.prototype.Dk=(0,z.O)(3,function(a,b){this.nm=a;this.Vc=b||this.Vc;var c=this.td[a]=new z.fu;z.wt.B();var d=this.d.u.v(),f=(0,z.t)(this.sD,this,a),g=(0,z.t)(this.rD,this,a),h=this.d.ca.ik,d=d.get(z.W.wc),h=z.w.ot(d,h)+String(a)+".json";(0,z.xt)(0,h,f,g);return c});z.lE.prototype.Dk=(0,z.O)(2,function(a,b){this.gk||(this.gk=new DI(this.H));var c=this.gk,d=CI(c,a,b);return c.Dk(d,a)});(0,z.v)(KI,z.zl);(0,z.ba)(KI);
KI.prototype.lE=function(a){var b={};b.ik=a[z.wE.Yx];var c=a[z.wE.Zx];c&&(b.WK=c);if(c=a[z.wE.$x]||z.cg&&(0,z.da)(z.rE.sp))b.eB=c;b.em=a[z.wE.cy]?!0:!1;c=a[z.wE.JA];b.zK=c?c:!1;if(c=a[z.wE.fy])b.ka=c;if(c=a[z.wE.yf])b.si=c;if(c=a[z.wE.jy])b.Dt=c;b.xi=(0,z.Al)(this,a[z.wE.oy]);if(c=a[z.wE.wy])b.vk=c;if(c=a[z.wE.Iz])b.yn=c;if(c=a[z.wE.Yz])b.$w=c;c=a[z.wE.eA];null!=c&&(b.fx=c);if(c=a[z.wE.qy]||!1)b.Na=c;b.readOnly=a[z.wE.READ_ONLY]||!1;if(c=a[z.wE.CA])b.QG=c;if(c=a[z.wE.ty])b.Ip=c;b.Le=a[z.wE.wc];b.cu=
(0,z.Bl)(a[z.wE.Ux]);c=a[z.wE.Wx];b.Wl=(0,z.ga)(c)?c:!0;a=a[z.wE.Qy];b.Np=(0,z.ga)(a)?a:!0;return b};(0,z.v)(LI,z.Kj);LI.prototype.Ww=function(a){this.Yh=new z.st(this);this.Ys=new z.up(this,a);this.Zb=new z.Gf(this);this.Qa=new z.Vt(this,a);this.$k=new z.bu(this);this.u=new z.Ct(this,a);this.pb=new z.lE(this,a);new z.nf;this.Sn=new z.Uu(this,a);this.xb=new z.Uw(this)};(0,z.v)(MI,z.ID);z.e=MI.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.Tv=b.v().Sd();a.eR=!z.H.get(z.H.j.Hc);a.Tk=b.Tk(z.H.id);a.LL=2===c.get(z.W.Yj);a.KL=3===c.get(z.W.Yj);a.k={wQ:z.Y.get(z.Y.g.As),zQ:z.Y.get(z.Y.g.Bs),RP:z.Y.get(z.Y.g.hz),dw:z.Y.get(z.Y.g.Fs),ew:z.Y.get(z.Y.g.Gs),Kn:z.Y.get(z.Y.g.kA),bo:z.Y.get(z.Y.g.Ro),zT:z.Y.get(z.Y.g.yA)};return a};
z.e.C=function(a){MI.b.C.call(this,a);a=this.c;var b;b=this.s();var c=(0,z.Gt)(b),d;d=b.Tv?'\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.eR?b.Tk?(0,z.R)(b.k.zQ):(0,z.R)(b.k.wQ):"")+"\x3c/a\x3e":"";b=c+d+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.R)(b.k.dw)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(b.k.Kn)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
(0,z.R)(b.k.ew)+"\x3c/a\x3e"+(b.LL?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(b.k.Kn)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+(0,z.R)(b.k.zT)+"\x3c/a\x3e":"")+(b.KL?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(b.k.Kn)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+(0,z.R)(b.k.RP)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e';a.innerHTML=b;this.Ck=this.n("fyre-follow-conversation");this.Qr=
this.n("fyre-stream-sort-hot-threads")||null;this.lx=this.n("fyre-stream-sort-top-comments")||null;this.bg=this.n("fyre-stream-sort-back");this.vl=this.n("fyre-stream-sort-newest");this.kx=this.n("fyre-stream-sort-oldest");this.fG=this.n("fyre-stream-sort-options");this.Oc=this.n("fyre-content-loading");this.qd()};z.e.l=function(){MI.b.l.call(this);var a=this.p();z.H.on(z.H.qa.hg,this.Ui,this);a.f(this.c,"click",this.ab);(0,z.x)([3,4,5],function(b){(0,z.JD)(this,a,b)},this);NI(this,a)};
z.e.ab=function(a){a.preventDefault();a=a.target;if(!(0,z.hi)(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.bg)if(a===this.Ck)this.qD();else switch(OI(this,a),this.ul(),a){case this.Qr:this.kC();break;case this.lx:this.dispatchEvent({type:"sortTopComments",yb:(0,z.t)(this.qd,this)});break;case this.vl:this.tm("new");break;case this.kx:this.tm("old")}};z.e.Uh=function(a,b){a&&this.Xw(b);(0,z.Lm)(this.fG,"display",a?"none":"block");(0,z.Lm)(this.bg,"display",a?"block":"none")};
z.e.Xw=function(a){var b=this.vl,c=this.tm,d=z.Y.get(z.Y.g.ls);4===a&&(b=this.Qr,c=this.kC,d=z.Y.get(z.Y.g.hH));this.bg.innerHTML=d;this.p().gf(this.bg,"click",(0,z.t)(function(a){a.stopPropagation();this.Uh(!1);OI(this,b);c.apply(this)},this))};z.e.Vm=function(a){a.stopPropagation();this.Uh(!1);OI(this,this.vl);this.tm()};z.e.oq=function(a){var b=a.yb;(0,z.D)(a,{yb:(0,z.t)(function(){b();this.Uh(!0,4)},this)})};
z.e.tm=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",yb:(0,z.t)(this.qd,this)})};z.e.kC=function(){this.dispatchEvent({type:"sortHotThreads",yb:(0,z.t)(this.qd,this)})};z.e.qD=function(){var a=this.d.u;a.v();var b=z.H.j;z.H.id?(b=a.Tk(z.H.get(b.Y)),a.Ki(!b),a=b?z.Y.get(z.Y.g.As):z.Y.get(z.Y.g.Bs),this.Ck.innerHTML=a):(0,z.Uh)(this.d.Zb,(0,z.t)(this.qD,this))};
z.e.Ui=function(){var a=this.d.u,b=a.v(),c=z.H.j,b=!b.Sd()||z.H.get(c.Hc);this.Ck&&(b?(0,z.T)(this.Ck,!1):(a=a.Tk(z.H.id)?z.Y.get(z.Y.g.Bs):z.Y.get(z.Y.g.As),this.Ck.innerHTML=a,(0,z.T)(this.Ck,!0)))};z.e.h=function(){MI.b.h.call(this);z.H.off(null,null,this)};(0,z.v)(PI,MI);PI.prototype.C=function(a){this.c=a;(0,z.Fl)(a,HI,this.s());this.vl=this.n("fyre-stream-sort-newest");this.kx=this.n("fyre-stream-sort-oldest");this.fG=this.n("fyre-stream-sort-options");this.Oc=this.n("fyre-content-loading");this.qd()};PI.prototype.tm=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",Xh:this.nT.Xh,direction:a,yb:(0,z.t)(this.qd,this)})};
PI.prototype.s=function(){return{k:{TK:z.Y.get(z.Y.g.cH),dw:z.Y.get(z.Y.g.Fs),ew:z.Y.get(z.Y.g.Gs),Kn:z.Y.get(z.Y.g.kA),bo:z.Y.get(z.Y.g.Ro)}}};(0,z.v)(QI,z.$v);z.e=QI.prototype;z.e.hm=function(a){this.clear();(0,z.T)(this.c,!0);this.Vc=a};z.e.clear=function(){this.Ue.ud();this.Eb={};this.Mk=[];this.Ug=this.kk=null;for(this.mx=[];this.ha&&0!=this.ha.length;)this.En(0).q()};z.e.C=function(a){QI.b.C.call(this,a);(0,z.Fl)(this.c,z.Ht,this.s());this.zj=this.n("fyre-stream-content");this.Vh=this.n("fyre-stream-more");this.Ha.S(this.Vh);(0,z.T)(this.Vh,!1)};z.e.h=function(){this.Ha&&this.Ha.q();this.Ha=null;QI.b.h.call(this)};
z.e.l=function(){QI.b.l.call(this);this.p().f(this.Ha,"showMore",this.kv)};z.e.s=function(){return{lg:z.w.J.ub,lC:!!this.Ha,k:{cx:z.Y.get(z.Y.g.dH)}}};z.e.lv=function(){this.Ha.Mr()};z.e.vw=function(){this.dispatchEvent({type:this.Ns,direction:this.Vc,target:this,yb:(0,z.t)(this.lv,this),Ji:(0,z.t)(this.OD,this)})};z.e.Rn=function(){var a=this.H.pb.gk,b=this.Vc,c=a.d.u.v(),b="old"===b,c=c.get(z.W.vo),c=!b&&a.nm>-c;b&&-1>a.nm||c?this.Ha.show():this.Ha.gb()};
z.e.start=function(){this.Pk||(this.vw(),this.Pk=!0)};(0,z.v)(RI,z.GD);RI.prototype.s=function(){var a=this.m.get(z.W.Dd),b,c;this.m.Sd()?(b=z.Y.get(z.Y.g.LI),c=z.Y.get(z.Y.g.mz)):(b=z.Y.get(z.Y.g.zf),c=z.Y.get(z.Y.g.Fl));(0,z.Fa)(b,"%s")||(b="%s "+b);(0,z.Fa)(c,"%s")||(c="%s "+c);switch(a){case 1:b=(0,z.ua)(b,a);break;default:b=(0,z.ua)(c,a)}return{k:{Ft:b}}};RI.prototype.Kx=function(){var a=this.c,b;b=this.s();b="\x3cspan\x3e"+(0,z.R)(b.k.Ft)+"\x3c/span\x3e";a.innerHTML=b};(0,z.v)(SI,z.Cs);SI.prototype.Un=200;SI.prototype.vh=function(){return new TI(this.yc)};SI.prototype.s=function(){var a={};a.message=this.Cx;return a};(0,z.v)(TI,z.ws);
TI.prototype.Cc=function(a,b,c){var d=(0,z.kn)(this.element),d=new z.Dh(d.width,d.height+25);b=(0,z.qs)(this.element,this.fh,a,b,d,c,9);(0,z.Sm)(a.lastChild,0);b&&(d=new z.Dh(0,-5),(0,z.qs)(this.element,2,a,1,d,c,5),(0,z.Sm)(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};(0,z.v)(UI,z.U);z.e=UI.prototype;z.e.o=function(){this.c=(0,z.Il)(GI,this.s())};z.e.l=function(){UI.b.l.call(this);this.La=new SI(this.c,this.m.get("displayName"));this.p().f(this.c,"click",this.ab)};z.e.h=function(){UI.b.h.call(this);this.La&&this.La.q()};z.e.s=function(){var a=z.Pd,b={};b.kd=this.m.get(a.Ua);b.Qb=this.m.get(a.Lj);b.W=this.m.get(a.$);b.id=this.m.id;b.TP=this.m.id.replace(/[@.]/g,"-");b.za=this.m.get(a.nb);return b};
z.e.ab=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};(0,z.v)(VI,z.U);z.e=VI.prototype;z.e.qz=10;z.e.h=function(){VI.b.h.call(this);delete this.Tb};z.e.N=function(){VI.b.N.call(this);this.Tb.off(null,null,this)};z.e.ZC=function(a){a=new UI(a);var b=this.Zc();if(b===this.qz){var c=this.En(b-1);c&&(c.q(),b--)}0<b?this.he(a,0,!0):this.G(a,!0)};z.e.$O=function(a){var b;this.Xc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.e.yh=function(){this.Tb.on(this.Tb.qa.js,this.ZC,this);this.Tb.on(this.Tb.qa.Js,this.$O,this);var a=this.Tb.Wb.reverse().slice(0,this.qz);(0,z.x)(a,this.ZC,this)};(0,z.v)(WI,VI);(0,z.v)(XI,z.HD);XI.prototype.C=function(a){XI.b.C.call(this,a);this.qj()};XI.prototype.qj=function(){this.c.innerHTML=(0,z.Lt)(this.s())};(function(a,b){function c(){var a=B.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){B.XS||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,function(a){b[a]=d(a);g.createElement(a);
return'c("'+a+'")'})+");return n}")(B,g)}function f(a){var b;if(a.PL)return a;if(B.WS&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";b=!!c.insertBefore(b.lastChild,
c.firstChild)}r||(b=!d(a));b&&(a.PL=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,r;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.cQ&&a.cQ("#modernizr{}",function(b){b.hidden=!0;m="none"==(a.getComputedStyle?
a.getComputedStyle(b,null):b.currentStyle).display});r=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var B={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==g.WS,shivMethods:!1!==
g.XS,type:"default",shivDocument:f};f(b)})(z.u.window,z.u.document);(0,z.v)(YI,z.QD);
YI.prototype.DF=function(a,b){if(!this.Ra){this.F=b;var c=b.get(z.W.jg),d=b.get(z.W.Ed);this.gs=new z.ND(c,d,a.ca.Na);this.G(this.gs);this.qp=new RI(a.u.v());this.G(this.qp);this.Xq=null;b.dn()&&(this.ht=new PI(a),this.G(this.ht),this.hk=new QI(a),this.G(this.hk),EI(this.ht,{Xh:this.hk}));this.Qg=new MI(a);this.G(this.Qg);this.Qq((0,z.t)(function(a){this.qb=a;this.G(this.qb);a=this.qb;this.aa&&a&&a.S(this.pe,!0)},this));b.get(z.W.Jl)&&!z.cg&&FI(this.F)&&(this.F.Fh()||this.F.Sd()||this.Ru())}};
YI.prototype.s=function(){return{zG:z.w.J.Dx,AG:(0,window.encodeURIComponent)(String(window.location.href)),Na:this.d.ca.Na,Fh:this.F.Fh(),Sd:this.F.Sd(),Xt:!this.d.ca.em&&!z.w.eC,hQ:this.d.ca.em,dn:this.F.dn()}};z.nw={cU:"fyre-archive-stream",dU:"fyre-archive-stream-header",tX:"fyre-top-content-stream",MX:"fyre-widget",Jl:"fyre-featured-content-wrapper"};(0,z.D)(z.nw,z.iH);z.e=YI.prototype;
z.e.o=function(){this.c=(0,z.Il)(II,this.s());var a=this.F.get(z.W.Yj);if(1!==a){var b=this.d.xb,a=2===a?3:4,c=this.n("fyre-top-content-stream");(0,z.Vw)(b,a,c,this)}this.uq.S(this.n(z.nw.AI));this.hk&&(b=this.n("fyre-archive-stream-header"),this.ht.S(b),this.hk.S(this.n("fyre-archive-stream")));this.gh(1);this.pe=this.n(z.nw.Mj);b=ZI(this);(0,z.T)(this.pe,b)};
z.e.l=function(){YI.b.l.call(this);var a=this.qb;this.aa&&a&&a.S(this.pe,!0);this.d.O.eo("stream_data_received",this.aO,this);this.p().f(this,"request_content_context",this.CN).f(this,"request_content_reply",this.bP);this.hk&&this.hk.start()};z.e.yh=function(){this.Cm&&this.Cm.yh();this.Uf.yh()};z.e.aO=function(){var a=this.F,b=a.get(z.W.Pj);z.yh||b||(b=(0,z.t)(function(){this.Xq=new z.dJ(this.d,a.get(z.W.Ed));this.G(this.Xq,!0)},this),(0,z.qc)(z.w.J.ub+z.w.lf.Xq,null,null,b))};
z.e.Ru=function(){var a=new z.yC(this.xE,this);a.hF=(0,z.t)(this.uS,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);(0,z.qc)(z.w.J.ub+z.w.lf.oM,null,null,b)};z.e.uS=function(){var a=this.n("fyre-featured-content-wrapper");this.ju=new z.yH(this.d);this.G(this.ju);this.ju.S(a);this.ju.Cg()};z.e.Qq=function(a){if(!this.d.ca.readOnly){var b=this.d.u.v();(0,z.kv)(z.iv.B(),"main",a,{H:this.d,lj:"new"},b);z.H.on(z.H.Ic(z.H.j.Y),(0,z.t)(this.ad,this))}};
z.e.ad=function(){var a=ZI(this);(0,z.T)(this.pe,a)};z.e.xg=function(){0<(0,z.An)(this,this.qb)&&(this.removeChild(this.qb),this.qb.q());this.Qq((0,z.t)(function(a){this.qb=a;this.G(this.qb);a=this.qb;this.aa&&a&&a.S(this.pe,!0);(0,z.T)(this.pe,!0)},this))};z.e.Bh=function(a){null!=a&&(this.d.xb.Ik(1),(0,window.setTimeout)((0,z.t)(function(){this.Ra||(0,z.RD)(this,a)},this),3E3))};z.e.CN=function(a){(0,z.RD)(this,a.jm)};z.e.bP=function(a){(0,z.RD)(this,a.jm,function(a){(0,z.mv)(a.jc)})};
z.e.h=function(){YI.b.h.call(this);this.F&&(this.F.off(null,null,this),this.F=null)};(0,z.v)($I,z.jx);z.e=$I.prototype;z.e.Qd=function(a,b){$I.b.Qd.call(this,a,b);a.f(b,"repliesExpanded",this.nD);a.f(b,"sortHotThreads",this.kP);a.f(b,"sortOrderChanged",this.RD);a.f(b,"sortTopComments",this.lP);a.f(b,"archiveShowMore",this.lN);a.f(b,"archiveSortOrderChanged",this.mN)};
z.e.lN=function(a){var b=a.yb||z.n;a=(0,z.t)(this.ue,this,a.target);var c=this.d.pb;c.gk||(c.gk=new DI(c.H));var c=c.gk,d=CI(c),f=c.$d[d];f&&(c.nm=d);if(f)b(),a(f);else{c=this.d.pb.Dk();d=c.j.Qe;if(c.get(d))b();else c.on(c.Ic(d),b,this);(0,z.kx)(this,c,a)}};z.e.Nu=function(a,b){var c=2===b.gd,d=1!==b.gd;switch(b.type){case 0:var f=this.d.u.v(),f=(0,z.yk)(b,f),g=f.get(z.Lk),g=this.d.u.Za().get(g);f.set(z.zk,g);a.dv(f,c,d)}};
z.e.KD=function(a){if(1!==this.Tl){var b=this.jT.Qg;b.Uh(!1);OI(b,b.vl);(0,z.D)(a,{direction:"new",yb:z.n});this.RD(a)}};z.e.mN=function(a){(0,z.lx)(this);a.Xh.hm(a.direction);var b=this.d.pb.Dk(a.direction,!0),c=(0,z.t)(function(b){a.yb();this.ue(a.Xh,b)},this);(0,z.kx)(this,b,c,a.Ji)};z.e.RD=function(a){var b=(0,z.nx)(this,1);(0,z.Iu)(this.d.pb);b.hm(a.direction);var c=(0,z.Hu)(this.d.pb,a.direction),d=(0,z.t)(function(c){a.yb();this.ue(b,c)},this);(0,z.kx)(this,c,d,a.Ji)};
z.e.lP=function(a){var b=(0,z.nx)(this,3),c=this.d.pb.rh("likes");(0,z.kx)(this,c,(0,z.t)(function(c){a.yb();(0,z.sb)(c)?(0,z.Zv)(b):this.ue(b,c)},this))};z.e.kP=function(a){var b=(0,z.nx)(this,4),c=this.d.pb.uh();(0,z.kx)(this,c,(0,z.t)(function(c){a.yb();(0,z.sb)(c)?(0,z.Zv)(b):this.ue(b,c)},this))};(0,z.v)(aJ,z.qr);z.e=aJ.prototype;z.e.c=null;z.e.h=function(){aJ.b.h.call(this);this.Tr.q();this.DB.q();this.Lb.aa&&this.Lb.q();this.xf&&this.xf.q();delete this.xf};z.e.Ok=function(a){aJ.b.Ok.call(this,a);this.Tr=new $I(this.d);this.Tr.handle(a);this.DB=new z.ix(this.d);this.DB.handle(a)};z.e.tx=function(){this.d.Yh.stop()};z.e.mT=function(){this.d.$k.stop()};z.e.wj=function(){this.d.Yh.start()};z.e.kT=function(){this.d.$k.start()};
z.e.wa=function(){this.xf&&this.xf.q();this.Lb.wa(this.c);var a=(0,z.sr)(this);this.Lb.Bh(a);this.d.O.L("render_complete")};(0,z.v)(bJ,z.tl);bJ.prototype.TA=KI.B();bJ.prototype.h=function(){bJ.b.h.call(this);this.stop();delete this.ca;delete this.ia;cJ(this);(0,z.yl)(this);this.Ii&&(this.Ii.q(),delete this.Ii)};bJ.prototype.Ax=function(){this.stop();cJ(this);bJ.b.Ax.call(this)};z.kg.main.ih.ka(bJ);})(fyre.conv);
