var sitesBySilo = {
            "style": [{"label": "HighSnobiety", "url": "http://www.highsnobiety.com", "dfp": "cmn_highsnobiety", "kw": "s_sty", "feature": 1},
                      {"label": "Selectism", "url": "http://www.selectism.com", "dfp": "cmn_selectism", "kw": "s_sty", "feature": 1},
                      {"label": "PorHomme", "url": "http://www.porhomme.com", "dfp": "cmn_porhomme", "kw": "s_sty", "feature": 1},
                      {"label": "FreshnessMag", "url": "http://www.freshnessmag.com", "dfp": "cmn_freshnessmag", "kw": "s_sty", "feature": 1},
                      {"label": "Complex Style", "url": "http://www.complex.com/style", "dfp": "cmn_complex", "kw": "s_sty", "feature": 1},
                      {"label": "BarbershopConnect", "url": "http://www.barbershopconnect.com", "dfp": "cmn_barbershopconnect", "kw": "s_sty", "feature": 0},
                      {"label": "ApetoGentleman", "url": "http://www.apetogentleman.com", "dfp": "cmn_apetogentleman", "kw": "s_sty", "feature": 0},
                      {"label": "ArrestedMotion", "url": "http://www.arrestedmotion.com", "dfp": "cmn_arrestedmotion", "kw": "s_sty", "feature": 0},
                      {"label": "Highsnobette", "url": "http://www.highsnobette.com", "dfp": "cmn_highsnobette", "kw": "s_sty", "feature": 0},
                      {"label": "Juxtapoz", "url": "http://www.juxtapoz.com", "dfp": "cmn_juxtapoz", "kw": "s_sty", "feature": 0},
                      {"label": "KarmaloopTV", "url": "http://www.karmalooptv.com", "dfp": "cmn_karmalooptv", "kw": "s_sty", "feature": 0},
                      {"label": "Kineda", "url": "http://www.kineda.com", "dfp": "cmn_kineda", "kw": "s_sty", "feature": 0},
                      {"label": "MaestroKnows", "url": "http://www.maestroknows.com", "dfp": "cmn_maestroknows", "kw": "s_sty", "feature": 0},
                      {"label": "MechanicalDummy", "url": "http://www.mechanicaldummy.com", "dfp": "cmn_mechanicaldummy", "kw": "s_sty", "feature": 0},
                      {"label": "RadCollector", "url": "http://www.radcollector.com", "dfp": "cmn_radcollector", "kw": "s_sty", "feature": 0},
                      {"label": "RawrDenim", "url": "http://www.rawrdenim.com", "dfp": "cmn_rawrdenim", "kw": "s_sty", "feature": 0},
                      {"label": "Slamxhype", "url": "http://www.slamxhype.com", "dfp": "cmn_slamxhype", "kw": "s_sty", "feature": 0},
                      {"label": "StupidDOPE", "url": "http://www.stupiddope.com", "dfp": "cmn_stupiddope", "kw": "s_sty", "feature": 0},
                      {"label": "StyleEngine", "url": "http://www.styleengine.com", "dfp": "cmn_styleengine", "kw": "s_sty", "feature": 0},
                      {"label": "TheChoosyBeggar", "url": "http://www.thechoosybeggar.com", "dfp": "cmn_thechoosybeggar", "kw": "s_sty", "feature": 0},
                      {"label": "UpscaleHype", "url": "http://www.upscalehype.com", "dfp": "cmn_upscalehype", "kw": "s_sty", "feature": 0},
                      {"label": "MassAppeal", "url": "http://www.massappeal.com", "dfp": "cmn_massappeal", "kw": "s_sty", "feature": 0},
                      {"label": "IAmPacked", "url": "http://www.iampacked.com", "dfp": "cmn_iampacked", "kw": "s_sty", "feature": 0},
                      {"label": "FourPins", "url": "http://four-pins.com", "dfp": "cmn_fourpins", "kw": "s_sty", "feature": 0},
                      {"label": "RefinedGuy", "url": "http://www.refinedguy.com/", "dfp": "cmn_refinedguy", "kw": "s_sty", "feature": 0},
                      {"label": "12OzProphet", "url": "http://www.12ozprophet.com", "dfp": "cmn_12ozprophet", "kw": "s_sty", "feature": 0},
                      {"label": "ClutterMagazine", "url": "http://www.cluttermagazine.com", "dfp": "cmn_cluttermagazine", "kw": "s_sty", "feature": 0},
                      {"label": "StreetWearDeals", "url": "http://www.streetweardeals.com", "dfp": "cmn_streetweardeals", "kw": "s_sty", "feature": 0},
                      {"label": "InfiniteLegRoom", "url": "http://infinitelegroom.com", "dfp": "cmn_infinitelegroom", "kw": "s_sty", "feature": 0},
                      {"label": "HiConsumption", "url": "http://www.hiconsumption.com", "dfp": "cmn_hiconsumption", "kw": "s_sty", "feature": 0},
                      {"label": "Green-Label", "url": "http://www.green-label.com", "dfp": "cmn_green-label", "kw": "s_sty", "feature": 0},
                      {"label": "DMarge", "url": "http://www.dmarge.com", "dfp": "cmn_dmarge", "kw": "s_sty", "feature": 0}],

            "sneakers": [{"label": "NiceKicks", "url": "http://www.nicekicks.com", "dfp": "cmn_nicekicks", "kw": "s_sne", "feature": 1},
                      {"label": "KicksonFire", "url": "http://www.kicksonfire.com", "dfp": "cmn_kicksonfire", "kw": "s_sne", "feature": 1},
                      {"label": "SneakerNews", "url": "http://www.sneakernews.com", "dfp": "cmn_sneakernews", "kw": "s_sne", "feature": 1},
                      {"label": "SneakerFreaker", "url": "http://www.sneakerfreaker.com", "dfp": "cmn_sneakerfreaker", "kw": "s_sne", "feature": 1},
                      {"label": "Complex Sneakers", "url": "http://www.complex.com/sneakers", "dfp": "cmn_complex", "kw": "s_sne", "feature": 1},
                      {"label": "CelebKicks", "url": "http://www.celebkicks.com", "dfp": "cmn_celebkicks", "kw": "s_sne", "feature": 0},
                      {"label": "JordansDaily", "url": "http://www.jordansdaily.com", "dfp": "cmn_jordansdaily", "kw": "s_sne", "feature": 0},
                      {"label": "KicksDeals", "url": "http://www.kicksdeals.com", "dfp": "cmn_kicksdeals", "kw": "s_sne", "feature": 0},
                      {"label": "SneakerWareApp", "url": "http://www.sneakerwareapp.com", "dfp": "cmn_sneakerwareapp", "kw": "s_sne", "feature": 0},
                      {"label": "SneakerWatch", "url": "http://www.sneakerwatch.com", "dfp": "cmn_sneakerwatch", "kw": "s_sne", "feature": 0},
                      {"label": "TheShoeGame", "url": "http://www.theshoegame.com", "dfp": "cmn_theshoegame", "kw": "s_sne", "feature": 0},
                      {"label": "SneakerReport", "url": "http://sneakerreport.com", "dfp": "cmn_sneakerreport", "kw": "s_sne", "feature": 0},
                      {"label": "SoleCollector", "url": "http://solecollector.com", "dfp": "cmn_solecollector", "kw": "s_sne", "feature": 0}],

            "music": [{"label": "HipHopDX", "url": "http://www.hiphopdx.com", "dfp": "cmn_hiphopdx", "kw": "s_mus", "feature": 1},
                      {"label": "DJBooth", "url": "http://www.djbooth.net", "dfp": "cmn_djbooth", "kw": "s_mus", "feature": 1},
                      {"label": "AllHipHop", "url": "http://www.allhiphop.com", "dfp": "cmn_allhiphop", "kw": "s_mus", "feature": 1},
                      {"label": "2DopeBoyz", "url": "http://www.2dopeboyz.com", "dfp": "cmn_2dopeboyz", "kw": "s_mus", "feature": 1},
                      {"label": "Complex Music", "url": "http://www.complex.com/music", "dfp": "cmn_complex", "kw": "s_mus", "feature": 1},
                      {"label": "DoAndroidsDance", "url": "http://doandroidsdance.com", "dfp": "cmn_doandroidsdance", "kw": "s_mus", "feature": 0},
                      {"label": "AudioMack", "url": "http://www.audiomack.com", "dfp": "cmn_audiomack", "kw": "s_mus", "feature": 0},
                      {"label": "BallerStatus", "url": "http://www.ballerstatus.com", "dfp": "cmn_ballerstatus", "kw": "s_mus", "feature": 0},
                      {"label": "BeatsPerMinute", "url": "http://www.beatsperminute.com", "dfp": "cmn_beatsperminute", "kw": "s_mus", "feature": 0},
                      {"label": "BestofBothOffices", "url": "http://www.bestofbothoffices.com", "dfp": "cmn_bestofbothoffices", "kw": "s_mus", "feature": 0},
                      {"label": "BoomShots", "url": "http://www.boomshots.com", "dfp": "cmn_boomshots", "kw": "s_mus", "feature": 0},
                      {"label": "Dajaz1", "url": "http://www.dajaz1.com", "dfp": "cmn_dajaz1", "kw": "s_mus", "feature": 0},
                      {"label": "DatNewCudi", "url": "http://www.datnewcudi.com", "dfp": "cmn_datnewcudi", "kw": "s_mus", "feature": 0},
                      {"label": "Earmilk", "url": "http://www.earmilk.com", "dfp": "cmn_earmilk", "kw": "s_mus", "feature": 0},
                      {"label": "EgoTripLand", "url": "http://www.egotripland.com", "dfp": "cmn_egotripland", "kw": "s_mus", "feature": 0},
                      {"label": "FakeShoreDrive", "url": "http://www.fakeshoredrive.com", "dfp": "cmn_fakeshoredrive", "kw": "s_mus", "feature": 0},
                      {"label": "FreeOnSmash", "url": "http://www.freeonsmash.com", "dfp": "cmn_freeonsmash", "kw": "s_mus", "feature": 0},
                      {"label": "HypeVideos", "url": "http://www.hypevideos.com", "dfp": "cmn_hypevideos", "kw": "s_mus", "feature": 0},
                      {"label": "IllRoots", "url": "http://www.illroots.com", "dfp": "cmn_illroots", "kw": "s_mus", "feature": 0},
                      {"label": "LilWayneHQ", "url": "http://www.lilwaynehq.com", "dfp": "cmn_lilwaynehq", "kw": "s_mus", "feature": 0},
                      {"label": "LiveMixTapes", "url": "http://www.livemixtapes.com", "dfp": "cmn_livemixtapes", "kw": "s_mus", "feature": 0},
                      {"label": "LX-Goods", "url": "http://www.lx-goods.com", "dfp": "cmn_lxgoods", "kw": "s_mus", "feature": 0},
                      {"label": "MissInfoTV", "url": "http://www.missinfo.tv", "dfp": "cmn_missinfo", "kw": "s_mus", "feature": 0},
                      {"label": "NahRight", "url": "http://www.nahright.com", "dfp": "cmn_nahright", "kw": "s_mus", "feature": 0},
                      {"label": "PigeonsandPlanes", "url": "http://www.pigeonsandplanes.com", "dfp": "cmn_pigeonsandplanes", "kw": "s_mus", "feature": 0},
                      {"label": "Refined Hype", "url": "http://www.refinedhype.com", "dfp": "cmn_refinedhype", "kw": "s_mus", "feature": 0},
                      {"label": "TheMaskedGorilla", "url": "http://www.themaskedgorilla.com", "dfp": "cmn_themaskedgorilla", "kw": "s_mus", "feature": 0},
                      {"label": "VibeToThis", "url": "http://www.vibetothis.com", "dfp": "cmn_vibetothis", "kw": "s_mus", "feature": 0},
                      {"label": "VladTV", "url": "http://www.vladtv.com", "dfp": "cmn_vladtv", "kw": "s_mus", "feature": 0},
                      {"label": "YouHeardThatNew", "url": "http://www.youheardthatnew.com", "dfp": "cmn_youheardthatnew", "kw": "s_mus", "feature": 0},
                      {"label": "YoungMoneyHQ", "url": "http://www.youngmoneyhq.com", "dfp": "cmn_youngmoneyhq", "kw": "s_mus", "feature": 0},
                      {"label": "MassAppeal", "url": "http://www.massappeal.com", "dfp": "cmn_massappeal", "kw": "s_mus", "feature": 0},
                      {"label": "InFlexWeTrust", "url": "http://www.inflexwetrust.com", "dfp": "cmn_inflexweTrust", "kw": "s_mus", "feature": 0},
                      {"label": "NME", "url": "http://www.nme.com", "dfp": "cmn_nme", "kw": "s_mus", "feature": 0},
                      {"label": "RareSoul", "url": "http://www.raresoul.com", "dfp": "cmn_raresoul", "kw": "s_mus", "feature": 0},
                      {"label": "SuperGlued", "url": "http://www.superglued.com", "dfp": "cmn_superglued", "kw": "s_mus", "feature": 0},
                      {"label": "RunTheTrap", "url":"http://www.runthetrap.com", "dfp": "cmn_runthetrap", "kw": "s_mus", "feature": 0}],

            "videoGames": [{"label": "GameRanx", "url": "http://www.gameranx.com", "dfp": "cmn_gameranx", "kw": "s_gam", "feature": 1},
                      {"label": "GameRant", "url": "http://www.gamerant.com", "dfp": "cmn_gamerant", "kw": "s_gam", "feature": 1},
                      {"label": "Shoryuken", "url": "http://www.shoryuken.com", "dfp": "cmn_shoryuken", "kw": "s_gam", "feature": 1},
                      {"label": "PastaPadre", "url": "http://www.pastapadre.com", "dfp": "cmn_pastapadre", "kw": "s_gam", "feature": 1},
                      {"label": "Complex Video Games", "url": "http://www.complex.com/video-games", "dfp": "cmn_complex", "kw": "s_gam", "feature": 1},
                      {"label": "PlaystationUniveristy", "url": "http://www.playstationuniveristy.com", "dfp": "cmn_planetplaystationuniversity", "kw": "s_gam", "feature": 0}],

            "popCulture": [{"label": "HollywoodHeavy", "url": "http://www.hollywoodheavy.com", "dfp": "cmn_hollywoodheavy", "kw": "s_pop", "feature": 1},
                      {"label": "MoeJackson", "url": "http://www.moejackson.com", "dfp": "cmn_moejackson", "kw": "s_pop", "feature": 1},
                      {"label": "CelebritySchoolPics", "url": "http://www.celebrityschoolpics.com", "dfp": "cmn_celebrityschoolpics", "kw": "s_pop", "feature": 1},
                      {"label": "FirstWeFeast", "url": "http://www.firstwefeast.com", "dfp": "cmn_firstwefeast", "kw": "s_pop", "feature": 1},
                      {"label": "Complex Pop Culture", "url": "http://www.complex.com/pop-culture", "dfp": "cmn_complex", "kw": "s_pop", "feature": 1},
                      {"label": "AnalogHype", "url": "http://www.analoghype.com", "dfp": "cmn_analoghype", "kw": "s_pop", "feature": 0},
                      {"label": "FreeOnSmash", "url": "http://www.freeonsmash.com", "dfp": "cmn_freeonsmash", "kw": "s_pop", "feature": 0},
                      {"label": "GetTheBigPicture.net", "url": "http://www.getthebigpicture.net", "dfp": "cmn_getthebigpicture", "kw": "s_pop", "feature": 0},
                      {"label": "GeekTyrant.com", "url": "http://www.geektyrant.com", "dfp": "cmn_geektyrant", "kw": "s_pop", "feature": 0},
                      {"label": "VideoGoneViral", "url": "http://www.videogoneviral.com", "dfp": "cmn_videogoneviral", "kw": "s_pop", "feature": 0},
                      {"label": "WorldOfDance", "url": "http://www.worldofdance.com", "dfp": "cmn_worldofdance", "kw": "s_pop", "feature": 0},
                      {"label": "TheFilmStage", "url": "http://thefilmstage.com", "dfp": "cmn_thefilmstage", "kw": "s_pop", "feature": 0},
                      {"label": "Ranker", "url": "http://ranker.com", "dfp": "cmn_ranker", "kw": "s_pop", "feature": 0},
                      {"label": "HipsterRunoff", "url": "http://hipsterrunoff.com", "dfp": "cmn_hipsterrunoff", "kw": "s_pop", "feature": 0},
                      {"label": "ShockMansion", "url": "http://shockmansion.com", "dfp": "cmn_shockmansion", "kw": "s_pop", "feature": 0},
                      {"label": "BehindTheHustle", "url": "http://behindthehustle.com", "dfp": "cmn_behindthehustle", "kw": "s_pop", "feature": 0},
                      {"label": "YouGottaEatThis", "url": "http://yougottaeatthis.com", "dfp": "cmn_yougottaeatthis", "kw": "s_pop", "feature": 0}],

            "sports": [{"label": "DimeMag", "url": "http://www.dimemag.com", "dfp": "cmn_dimemag", "kw": "s_spo", "feature": 1},
                      {"label": "TotalProSports", "url": "http://www.totalprosports.com", "dfp": "cmn_totalprosports", "kw": "s_spo", "feature": 1},
                      {"label": "RadCollector", "url": "http://www.radcollector.com", "dfp": "cmn_radcollector", "kw": "s_spo", "feature": 1},
                      {"label": "TheHoopDoctors", "url": "http://www.thehoopdoctors.com", "dfp": "cmn_thehoopdoctors", "kw": "s_spo", "feature": 1},
                      {"label": "Complex Sports", "url": "http://www.complex.com/sports", "dfp": "cmn_complex", "kw": "s_spo", "feature": 1},
                      {"label": "6Magazine", "url": "http://6magazineonline.com/", "dfp": "cmn_6magazineonline", "kw": "s_spo", "feature": 0},
                      {"label": "BallJunkie", "url": "http://balljunkie.com/", "dfp": "cmn_balljunkie", "kw": "s_spo", "feature": 0},
                      {"label": "AlreadyDigital", "url": "http://alreadydigital.com", "dfp": "cmn_alreadytv", "kw": "s_spo", "feature": 0},
                      {"label": "HighSchoolHoop", "url": "http://www.highschoolhoop.com", "dfp": "cmn_highschoolhoop", "kw": "s_spo", "feature": 0},
                      {"label": "JapaneseSportCars", "url": "http://www.japanesesportcars.com", "dfp": "cmn_japanesesportcars", "kw": "s_spo", "feature": 0},
                      {"label": "SheridanHoops", "url": "http://www.sheridanhoops.com", "dfp": "cmn_sheridanhoops", "kw": "s_spo", "feature": 0},
                      {"label": "TheCageDoctors", "url": "http://www.thecagedoctors.com", "dfp": "cmn_thecagedoctors", "kw": "s_spo", "feature": 0},
                      {"label": "TheDugoutDoctors", "url": "http://www.thedugoutdoctors.com", "dfp": "cmn_thedugoutdoctors", "kw": "s_spo", "feature": 0},
                      {"label": "TheOriginalWinger", "url": "http://www.theoriginalwinger.com", "dfp": "cmn_theoriginalwinger", "kw": "s_spo", "feature": 0},
                      {"label": "ThePigSkinDoctors", "url": "http://thepigskindoctors.com", "dfp": "cmn_thepigskindoctors", "kw": "s_spo", "feature": 0},
                      {"label": "ThePuckDoctors", "url": "http://thepuckdoctors.com", "dfp": "cmn_thepuckdoctors", "kw": "s_spo", "feature": 0},
                      {"label": "HouseofHighlights", "url": "http://houseofhighlights.com", "dfp": "cmn_houseofhighlights", "kw": "s_spo", "feature": 0}]
        };
